// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"ruleGoKratos/internal/biz"
	"ruleGoKratos/internal/conf"
	"ruleGoKratos/internal/data"
	"ruleGoKratos/internal/server"
	"ruleGoKratos/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	ruleGoRepo := data.NewRuleGoRepo(dataData, logger)
	ruleGo, err := data.NewRuleEngine(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	ruleGoUsecase := biz.NewRuleGoUsecase(ruleGoRepo, logger, ruleGo)
	ruleGoService := service.NewRuleGoService(ruleGoUsecase)
	grpcServer := server.NewGRPCServer(confServer, ruleGoService, logger)
	httpServer := server.NewHTTPServer(confServer, ruleGoService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
