// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"ruleGoKratos/internal/biz"
	"ruleGoKratos/internal/biz/playground/agentpool"
	"ruleGoKratos/internal/biz/playground/trace"
	"ruleGoKratos/internal/biz/playground/workflow"
	"ruleGoKratos/internal/conf"
	"ruleGoKratos/internal/data"
	data2 "ruleGoKratos/internal/data/playground"
	"ruleGoKratos/internal/server"
	"ruleGoKratos/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	confServer := bootstrap.Server
	confData := bootstrap.Data
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	ruleChainRepo := data.NewRuleChainRepo(dataData, logger)
	runLogRepo := data.NewRunLogRepo(dataData, logger)
	config := data.NewRuleConfig()
	agentUsecase := biz.NewAgentUsecase(logger, bootstrap)
	taskBoardRepo := data.NewTaskBoardRepo(dataData, logger)
	taskBoardUsecase := biz.NewTaskBoardUsecase(taskBoardRepo)
	serviceManagementRepo := data.NewServiceManagementRepo(dataData, logger)
	serviceManagementUsecase := biz.NewServiceManagementUsecase(serviceManagementRepo)
	ruleGo, err := data.NewRuleEngine(confData, config, agentUsecase, taskBoardUsecase, serviceManagementUsecase)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	ruleChainUsecase := biz.NewRuleChainUsecase(ruleChainRepo, runLogRepo, logger, ruleGo, config, agentUsecase, bootstrap)
	componentRegulationRepo := data.NewComponentRegulationRepo(dataData, logger)
	componentRegulationUsecase := biz.NewComponentRegulationUsecase(componentRegulationRepo, logger)
	componentUseRuleRepo := data.NewComponentUseRuleRepo(dataData, logger)
	componentUseRuleUsecase := biz.NewComponentUseRuleUsecase(componentUseRuleRepo, logger)
	mdWorkflowRepo := data.NewMdWorkflowRepo(dataData, logger)
	mdWorkflowUsecase := biz.NewMdWorkflowUsecase(mdWorkflowRepo, logger)
	runLogUsecase := biz.NewRunLogUsecase(runLogRepo, logger)
	ruleGoService := service.NewRuleGoService(ruleChainUsecase, componentRegulationUsecase, componentUseRuleUsecase, mdWorkflowUsecase, runLogUsecase)
	runLogService := service.NewRunLogService(runLogUsecase)
	componentService := service.NewComponentService(runLogUsecase, componentUseRuleUsecase)
	agentPoolRepo := data.NewPlaygroundAgentPoolRepo(dataData)
	agentPoolService := agentpool.NewAgentPoolService(agentPoolRepo)
	adminService := service.NewAdminService(logger, bootstrap, agentPoolService)
	chatService := service.NewChatService(agentUsecase)
	taskBoardService := service.NewTaskBoardService(taskBoardUsecase, serviceManagementUsecase, logger)
	scheduledTaskRepo := data.NewScheduledTaskRepo(dataData, logger)
	scheduledTaskScheduler := biz.NewScheduledTaskScheduler()
	scheduledTaskUsecase := biz.NewScheduledTaskUsecase(scheduledTaskRepo, ruleChainUsecase, scheduledTaskScheduler, logger)
	scheduledTaskService := service.NewScheduledTaskService(scheduledTaskUsecase)
	grpcServer := server.NewGRPCServer(confServer, ruleGoService, runLogService, componentService, adminService, chatService, taskBoardService, scheduledTaskService, logger)
	gormSchemeRepo := data.NewPlaygroundSchemeRepo(dataData)
	traceRepo := data2.NewTraceRepo()
	traceEngine := trace.NewTraceEngine(traceRepo)
	repo := data.NewPlaygroundRuntimeRepo(dataData)
	workflowService := workflow.NewWorkflowServiceWithRuntimeRepo(gormSchemeRepo, agentPoolService, traceEngine, agentUsecase, repo)
	playgroundService := service.NewPlaygroundService(agentPoolService, workflowService, logger)
	httpServer := server.NewHTTPServer(confServer, ruleGoService, runLogService, componentService, adminService, chatService, playgroundService, taskBoardService, scheduledTaskService, logger)
	app := newApp(logger, grpcServer, httpServer, scheduledTaskUsecase)
	return app, func() {
		cleanup()
	}, nil
}
