// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"ruleGoKratos/internal/biz"
	"ruleGoKratos/internal/conf"
	"ruleGoKratos/internal/data"
	"ruleGoKratos/internal/server"
	"ruleGoKratos/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	confServer := bootstrap.Server
	confData := bootstrap.Data
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	ruleChainRepo := data.NewRuleChainRepo(dataData, logger)
	runLogRepo := data.NewRunLogRepo(dataData, logger)
	config := data.NewRuleConfig()
	ruleGo, err := data.NewRuleEngine(confData, config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	ruleChainUsecase := biz.NewRuleChainUsecase(ruleChainRepo, runLogRepo, logger, ruleGo, config)
	componentRegulationRepo := data.NewComponentRegulationRepo(dataData, logger)
	componentRegulationUsecase := biz.NewComponentRegulationUsecase(componentRegulationRepo, logger)
	componentUseRuleRepo := data.NewComponentUseRuleRepo(dataData, logger)
	componentUseRuleUsecase := biz.NewComponentUseRuleUsecase(componentUseRuleRepo, logger)
	mdWorkflowRepo := data.NewMdWorkflowRepo(dataData, logger)
	mdWorkflowUsecase := biz.NewMdWorkflowUsecase(mdWorkflowRepo, logger)
	runLogUsecase := biz.NewRunLogUsecase(runLogRepo, logger)
	ruleGoService := service.NewRuleGoService(ruleChainUsecase, componentRegulationUsecase, componentUseRuleUsecase, mdWorkflowUsecase, runLogUsecase)
	runLogService := service.NewRunLogService(runLogUsecase)
	componentService := service.NewComponentService(runLogUsecase, componentUseRuleUsecase)
	mdWorkflowService := service.NewMdWorkflowService(mdWorkflowUsecase)
	adminService := service.NewAdminService(logger, bootstrap)
	grpcServer := server.NewGRPCServer(confServer, ruleGoService, runLogService, componentService, mdWorkflowService, adminService, logger)
	httpServer := server.NewHTTPServer(confServer, ruleGoService, runLogService, componentService, mdWorkflowService, adminService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
