// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/rulego/v1/admin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsReply, error)
	UploadSkill(ctx context.Context, in *UploadSkillRequest, opts ...grpc.CallOption) (*UploadSkillReply, error)
	ListMcpConfigs(ctx context.Context, in *ListMcpConfigsRequest, opts ...grpc.CallOption) (*ListMcpConfigsReply, error)
	CreateMcpConfig(ctx context.Context, in *CreateMcpConfigRequest, opts ...grpc.CallOption) (*McpConfigItem, error)
	UpdateMcpConfig(ctx context.Context, in *UpdateMcpConfigRequest, opts ...grpc.CallOption) (*UpdateMcpConfigReply, error)
	DeleteMcpConfig(ctx context.Context, in *DeleteMcpConfigRequest, opts ...grpc.CallOption) (*DeleteMcpConfigReply, error)
	// TestMcpConfig：http 模式用 SSE 连 endpoint；stdio 模式在本机拉起子进程。均执行 initialize 与 tools/list。
	TestMcpConfig(ctx context.Context, in *TestMcpConfigRequest, opts ...grpc.CallOption) (*TestMcpConfigReply, error)
	ListLlmConfigs(ctx context.Context, in *ListLlmConfigsRequest, opts ...grpc.CallOption) (*ListLlmConfigsReply, error)
	CreateLlmConfig(ctx context.Context, in *CreateLlmConfigRequest, opts ...grpc.CallOption) (*LlmConfigItem, error)
	UpdateLlmConfig(ctx context.Context, in *UpdateLlmConfigRequest, opts ...grpc.CallOption) (*UpdateLlmConfigReply, error)
	DeleteLlmConfig(ctx context.Context, in *DeleteLlmConfigRequest, opts ...grpc.CallOption) (*DeleteLlmConfigReply, error)
	CreateLlmModelEntry(ctx context.Context, in *CreateLlmModelEntryRequest, opts ...grpc.CallOption) (*LlmModelEntryItem, error)
	UpdateLlmModelEntry(ctx context.Context, in *UpdateLlmModelEntryRequest, opts ...grpc.CallOption) (*UpdateLlmModelEntryReply, error)
	DeleteLlmModelEntry(ctx context.Context, in *DeleteLlmModelEntryRequest, opts ...grpc.CallOption) (*DeleteLlmModelEntryReply, error)
	// RunTerminal 在服务端执行 shell 命令（仅管理端；cwd 须在白名单目录下）。
	RunTerminal(ctx context.Context, in *RunTerminalRequest, opts ...grpc.CallOption) (*RunTerminalReply, error)
	// GetLarkCliConfig 读取 lark-cli 配置文件（默认 ~/.lark-cli/config.json）及终端超时配置。
	GetLarkCliConfig(ctx context.Context, in *GetLarkCliConfigRequest, opts ...grpc.CallOption) (*GetLarkCliConfigReply, error)
	// SaveLarkCliConfig 写入 lark-cli 配置文件（须为合法 JSON）。
	SaveLarkCliConfig(ctx context.Context, in *SaveLarkCliConfigRequest, opts ...grpc.CallOption) (*SaveLarkCliConfigReply, error)
	// 工作区管理（统一走 proto/http 契约）
	ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (*ListWorkspacesReply, error)
	GetWorkspace(ctx context.Context, in *GetWorkspaceRequest, opts ...grpc.CallOption) (*GetWorkspaceReply, error)
	CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...grpc.CallOption) (*CreateWorkspaceReply, error)
	UpdateWorkspace(ctx context.Context, in *UpdateWorkspaceRequest, opts ...grpc.CallOption) (*UpdateWorkspaceReply, error)
	SyncWorkspace(ctx context.Context, in *SyncWorkspaceRequest, opts ...grpc.CallOption) (*SyncWorkspaceReply, error)
	DeleteWorkspace(ctx context.Context, in *DeleteWorkspaceRequest, opts ...grpc.CallOption) (*DeleteWorkspaceReply, error)
	// 可编排 Agent 配置管理
	ListManagedAgents(ctx context.Context, in *ListManagedAgentsRequest, opts ...grpc.CallOption) (*ListManagedAgentsReply, error)
	GetManagedAgent(ctx context.Context, in *GetManagedAgentRequest, opts ...grpc.CallOption) (*GetManagedAgentReply, error)
	CreateManagedAgent(ctx context.Context, in *CreateManagedAgentRequest, opts ...grpc.CallOption) (*CreateManagedAgentReply, error)
	UpdateManagedAgent(ctx context.Context, in *UpdateManagedAgentRequest, opts ...grpc.CallOption) (*UpdateManagedAgentReply, error)
	DeleteManagedAgent(ctx context.Context, in *DeleteManagedAgentRequest, opts ...grpc.CallOption) (*DeleteManagedAgentReply, error)
	ListSkillPackages(ctx context.Context, in *ListSkillPackagesRequest, opts ...grpc.CallOption) (*ListSkillPackagesReply, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsReply, error) {
	out := new(ListSkillsReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/ListSkills", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UploadSkill(ctx context.Context, in *UploadSkillRequest, opts ...grpc.CallOption) (*UploadSkillReply, error) {
	out := new(UploadSkillReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/UploadSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListMcpConfigs(ctx context.Context, in *ListMcpConfigsRequest, opts ...grpc.CallOption) (*ListMcpConfigsReply, error) {
	out := new(ListMcpConfigsReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/ListMcpConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateMcpConfig(ctx context.Context, in *CreateMcpConfigRequest, opts ...grpc.CallOption) (*McpConfigItem, error) {
	out := new(McpConfigItem)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/CreateMcpConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateMcpConfig(ctx context.Context, in *UpdateMcpConfigRequest, opts ...grpc.CallOption) (*UpdateMcpConfigReply, error) {
	out := new(UpdateMcpConfigReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/UpdateMcpConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteMcpConfig(ctx context.Context, in *DeleteMcpConfigRequest, opts ...grpc.CallOption) (*DeleteMcpConfigReply, error) {
	out := new(DeleteMcpConfigReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/DeleteMcpConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) TestMcpConfig(ctx context.Context, in *TestMcpConfigRequest, opts ...grpc.CallOption) (*TestMcpConfigReply, error) {
	out := new(TestMcpConfigReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/TestMcpConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListLlmConfigs(ctx context.Context, in *ListLlmConfigsRequest, opts ...grpc.CallOption) (*ListLlmConfigsReply, error) {
	out := new(ListLlmConfigsReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/ListLlmConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateLlmConfig(ctx context.Context, in *CreateLlmConfigRequest, opts ...grpc.CallOption) (*LlmConfigItem, error) {
	out := new(LlmConfigItem)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/CreateLlmConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateLlmConfig(ctx context.Context, in *UpdateLlmConfigRequest, opts ...grpc.CallOption) (*UpdateLlmConfigReply, error) {
	out := new(UpdateLlmConfigReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/UpdateLlmConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteLlmConfig(ctx context.Context, in *DeleteLlmConfigRequest, opts ...grpc.CallOption) (*DeleteLlmConfigReply, error) {
	out := new(DeleteLlmConfigReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/DeleteLlmConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateLlmModelEntry(ctx context.Context, in *CreateLlmModelEntryRequest, opts ...grpc.CallOption) (*LlmModelEntryItem, error) {
	out := new(LlmModelEntryItem)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/CreateLlmModelEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateLlmModelEntry(ctx context.Context, in *UpdateLlmModelEntryRequest, opts ...grpc.CallOption) (*UpdateLlmModelEntryReply, error) {
	out := new(UpdateLlmModelEntryReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/UpdateLlmModelEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteLlmModelEntry(ctx context.Context, in *DeleteLlmModelEntryRequest, opts ...grpc.CallOption) (*DeleteLlmModelEntryReply, error) {
	out := new(DeleteLlmModelEntryReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/DeleteLlmModelEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RunTerminal(ctx context.Context, in *RunTerminalRequest, opts ...grpc.CallOption) (*RunTerminalReply, error) {
	out := new(RunTerminalReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/RunTerminal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetLarkCliConfig(ctx context.Context, in *GetLarkCliConfigRequest, opts ...grpc.CallOption) (*GetLarkCliConfigReply, error) {
	out := new(GetLarkCliConfigReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/GetLarkCliConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) SaveLarkCliConfig(ctx context.Context, in *SaveLarkCliConfigRequest, opts ...grpc.CallOption) (*SaveLarkCliConfigReply, error) {
	out := new(SaveLarkCliConfigReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/SaveLarkCliConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (*ListWorkspacesReply, error) {
	out := new(ListWorkspacesReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/ListWorkspaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetWorkspace(ctx context.Context, in *GetWorkspaceRequest, opts ...grpc.CallOption) (*GetWorkspaceReply, error) {
	out := new(GetWorkspaceReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/GetWorkspace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...grpc.CallOption) (*CreateWorkspaceReply, error) {
	out := new(CreateWorkspaceReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/CreateWorkspace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateWorkspace(ctx context.Context, in *UpdateWorkspaceRequest, opts ...grpc.CallOption) (*UpdateWorkspaceReply, error) {
	out := new(UpdateWorkspaceReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/UpdateWorkspace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) SyncWorkspace(ctx context.Context, in *SyncWorkspaceRequest, opts ...grpc.CallOption) (*SyncWorkspaceReply, error) {
	out := new(SyncWorkspaceReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/SyncWorkspace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteWorkspace(ctx context.Context, in *DeleteWorkspaceRequest, opts ...grpc.CallOption) (*DeleteWorkspaceReply, error) {
	out := new(DeleteWorkspaceReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/DeleteWorkspace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListManagedAgents(ctx context.Context, in *ListManagedAgentsRequest, opts ...grpc.CallOption) (*ListManagedAgentsReply, error) {
	out := new(ListManagedAgentsReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/ListManagedAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetManagedAgent(ctx context.Context, in *GetManagedAgentRequest, opts ...grpc.CallOption) (*GetManagedAgentReply, error) {
	out := new(GetManagedAgentReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/GetManagedAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateManagedAgent(ctx context.Context, in *CreateManagedAgentRequest, opts ...grpc.CallOption) (*CreateManagedAgentReply, error) {
	out := new(CreateManagedAgentReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/CreateManagedAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateManagedAgent(ctx context.Context, in *UpdateManagedAgentRequest, opts ...grpc.CallOption) (*UpdateManagedAgentReply, error) {
	out := new(UpdateManagedAgentReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/UpdateManagedAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteManagedAgent(ctx context.Context, in *DeleteManagedAgentRequest, opts ...grpc.CallOption) (*DeleteManagedAgentReply, error) {
	out := new(DeleteManagedAgentReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/DeleteManagedAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListSkillPackages(ctx context.Context, in *ListSkillPackagesRequest, opts ...grpc.CallOption) (*ListSkillPackagesReply, error) {
	out := new(ListSkillPackagesReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.Admin/ListSkillPackages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility
type AdminServer interface {
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsReply, error)
	UploadSkill(context.Context, *UploadSkillRequest) (*UploadSkillReply, error)
	ListMcpConfigs(context.Context, *ListMcpConfigsRequest) (*ListMcpConfigsReply, error)
	CreateMcpConfig(context.Context, *CreateMcpConfigRequest) (*McpConfigItem, error)
	UpdateMcpConfig(context.Context, *UpdateMcpConfigRequest) (*UpdateMcpConfigReply, error)
	DeleteMcpConfig(context.Context, *DeleteMcpConfigRequest) (*DeleteMcpConfigReply, error)
	// TestMcpConfig：http 模式用 SSE 连 endpoint；stdio 模式在本机拉起子进程。均执行 initialize 与 tools/list。
	TestMcpConfig(context.Context, *TestMcpConfigRequest) (*TestMcpConfigReply, error)
	ListLlmConfigs(context.Context, *ListLlmConfigsRequest) (*ListLlmConfigsReply, error)
	CreateLlmConfig(context.Context, *CreateLlmConfigRequest) (*LlmConfigItem, error)
	UpdateLlmConfig(context.Context, *UpdateLlmConfigRequest) (*UpdateLlmConfigReply, error)
	DeleteLlmConfig(context.Context, *DeleteLlmConfigRequest) (*DeleteLlmConfigReply, error)
	CreateLlmModelEntry(context.Context, *CreateLlmModelEntryRequest) (*LlmModelEntryItem, error)
	UpdateLlmModelEntry(context.Context, *UpdateLlmModelEntryRequest) (*UpdateLlmModelEntryReply, error)
	DeleteLlmModelEntry(context.Context, *DeleteLlmModelEntryRequest) (*DeleteLlmModelEntryReply, error)
	// RunTerminal 在服务端执行 shell 命令（仅管理端；cwd 须在白名单目录下）。
	RunTerminal(context.Context, *RunTerminalRequest) (*RunTerminalReply, error)
	// GetLarkCliConfig 读取 lark-cli 配置文件（默认 ~/.lark-cli/config.json）及终端超时配置。
	GetLarkCliConfig(context.Context, *GetLarkCliConfigRequest) (*GetLarkCliConfigReply, error)
	// SaveLarkCliConfig 写入 lark-cli 配置文件（须为合法 JSON）。
	SaveLarkCliConfig(context.Context, *SaveLarkCliConfigRequest) (*SaveLarkCliConfigReply, error)
	// 工作区管理（统一走 proto/http 契约）
	ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesReply, error)
	GetWorkspace(context.Context, *GetWorkspaceRequest) (*GetWorkspaceReply, error)
	CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*CreateWorkspaceReply, error)
	UpdateWorkspace(context.Context, *UpdateWorkspaceRequest) (*UpdateWorkspaceReply, error)
	SyncWorkspace(context.Context, *SyncWorkspaceRequest) (*SyncWorkspaceReply, error)
	DeleteWorkspace(context.Context, *DeleteWorkspaceRequest) (*DeleteWorkspaceReply, error)
	// 可编排 Agent 配置管理
	ListManagedAgents(context.Context, *ListManagedAgentsRequest) (*ListManagedAgentsReply, error)
	GetManagedAgent(context.Context, *GetManagedAgentRequest) (*GetManagedAgentReply, error)
	CreateManagedAgent(context.Context, *CreateManagedAgentRequest) (*CreateManagedAgentReply, error)
	UpdateManagedAgent(context.Context, *UpdateManagedAgentRequest) (*UpdateManagedAgentReply, error)
	DeleteManagedAgent(context.Context, *DeleteManagedAgentRequest) (*DeleteManagedAgentReply, error)
	ListSkillPackages(context.Context, *ListSkillPackagesRequest) (*ListSkillPackagesReply, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (UnimplementedAdminServer) ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedAdminServer) UploadSkill(context.Context, *UploadSkillRequest) (*UploadSkillReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadSkill not implemented")
}
func (UnimplementedAdminServer) ListMcpConfigs(context.Context, *ListMcpConfigsRequest) (*ListMcpConfigsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMcpConfigs not implemented")
}
func (UnimplementedAdminServer) CreateMcpConfig(context.Context, *CreateMcpConfigRequest) (*McpConfigItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMcpConfig not implemented")
}
func (UnimplementedAdminServer) UpdateMcpConfig(context.Context, *UpdateMcpConfigRequest) (*UpdateMcpConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMcpConfig not implemented")
}
func (UnimplementedAdminServer) DeleteMcpConfig(context.Context, *DeleteMcpConfigRequest) (*DeleteMcpConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMcpConfig not implemented")
}
func (UnimplementedAdminServer) TestMcpConfig(context.Context, *TestMcpConfigRequest) (*TestMcpConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestMcpConfig not implemented")
}
func (UnimplementedAdminServer) ListLlmConfigs(context.Context, *ListLlmConfigsRequest) (*ListLlmConfigsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLlmConfigs not implemented")
}
func (UnimplementedAdminServer) CreateLlmConfig(context.Context, *CreateLlmConfigRequest) (*LlmConfigItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLlmConfig not implemented")
}
func (UnimplementedAdminServer) UpdateLlmConfig(context.Context, *UpdateLlmConfigRequest) (*UpdateLlmConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLlmConfig not implemented")
}
func (UnimplementedAdminServer) DeleteLlmConfig(context.Context, *DeleteLlmConfigRequest) (*DeleteLlmConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLlmConfig not implemented")
}
func (UnimplementedAdminServer) CreateLlmModelEntry(context.Context, *CreateLlmModelEntryRequest) (*LlmModelEntryItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLlmModelEntry not implemented")
}
func (UnimplementedAdminServer) UpdateLlmModelEntry(context.Context, *UpdateLlmModelEntryRequest) (*UpdateLlmModelEntryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLlmModelEntry not implemented")
}
func (UnimplementedAdminServer) DeleteLlmModelEntry(context.Context, *DeleteLlmModelEntryRequest) (*DeleteLlmModelEntryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLlmModelEntry not implemented")
}
func (UnimplementedAdminServer) RunTerminal(context.Context, *RunTerminalRequest) (*RunTerminalReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunTerminal not implemented")
}
func (UnimplementedAdminServer) GetLarkCliConfig(context.Context, *GetLarkCliConfigRequest) (*GetLarkCliConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLarkCliConfig not implemented")
}
func (UnimplementedAdminServer) SaveLarkCliConfig(context.Context, *SaveLarkCliConfigRequest) (*SaveLarkCliConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveLarkCliConfig not implemented")
}
func (UnimplementedAdminServer) ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkspaces not implemented")
}
func (UnimplementedAdminServer) GetWorkspace(context.Context, *GetWorkspaceRequest) (*GetWorkspaceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkspace not implemented")
}
func (UnimplementedAdminServer) CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*CreateWorkspaceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkspace not implemented")
}
func (UnimplementedAdminServer) UpdateWorkspace(context.Context, *UpdateWorkspaceRequest) (*UpdateWorkspaceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkspace not implemented")
}
func (UnimplementedAdminServer) SyncWorkspace(context.Context, *SyncWorkspaceRequest) (*SyncWorkspaceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncWorkspace not implemented")
}
func (UnimplementedAdminServer) DeleteWorkspace(context.Context, *DeleteWorkspaceRequest) (*DeleteWorkspaceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkspace not implemented")
}
func (UnimplementedAdminServer) ListManagedAgents(context.Context, *ListManagedAgentsRequest) (*ListManagedAgentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListManagedAgents not implemented")
}
func (UnimplementedAdminServer) GetManagedAgent(context.Context, *GetManagedAgentRequest) (*GetManagedAgentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManagedAgent not implemented")
}
func (UnimplementedAdminServer) CreateManagedAgent(context.Context, *CreateManagedAgentRequest) (*CreateManagedAgentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateManagedAgent not implemented")
}
func (UnimplementedAdminServer) UpdateManagedAgent(context.Context, *UpdateManagedAgentRequest) (*UpdateManagedAgentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateManagedAgent not implemented")
}
func (UnimplementedAdminServer) DeleteManagedAgent(context.Context, *DeleteManagedAgentRequest) (*DeleteManagedAgentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteManagedAgent not implemented")
}
func (UnimplementedAdminServer) ListSkillPackages(context.Context, *ListSkillPackagesRequest) (*ListSkillPackagesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSkillPackages not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/ListSkills",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListSkills(ctx, req.(*ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UploadSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UploadSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/UploadSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UploadSkill(ctx, req.(*UploadSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListMcpConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMcpConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListMcpConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/ListMcpConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListMcpConfigs(ctx, req.(*ListMcpConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateMcpConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMcpConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateMcpConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/CreateMcpConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateMcpConfig(ctx, req.(*CreateMcpConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateMcpConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMcpConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateMcpConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/UpdateMcpConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateMcpConfig(ctx, req.(*UpdateMcpConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteMcpConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMcpConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteMcpConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/DeleteMcpConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteMcpConfig(ctx, req.(*DeleteMcpConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_TestMcpConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMcpConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).TestMcpConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/TestMcpConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).TestMcpConfig(ctx, req.(*TestMcpConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListLlmConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLlmConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListLlmConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/ListLlmConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListLlmConfigs(ctx, req.(*ListLlmConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateLlmConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLlmConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateLlmConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/CreateLlmConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateLlmConfig(ctx, req.(*CreateLlmConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateLlmConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLlmConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateLlmConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/UpdateLlmConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateLlmConfig(ctx, req.(*UpdateLlmConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteLlmConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLlmConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteLlmConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/DeleteLlmConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteLlmConfig(ctx, req.(*DeleteLlmConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateLlmModelEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLlmModelEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateLlmModelEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/CreateLlmModelEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateLlmModelEntry(ctx, req.(*CreateLlmModelEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateLlmModelEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLlmModelEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateLlmModelEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/UpdateLlmModelEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateLlmModelEntry(ctx, req.(*UpdateLlmModelEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteLlmModelEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLlmModelEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteLlmModelEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/DeleteLlmModelEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteLlmModelEntry(ctx, req.(*DeleteLlmModelEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RunTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RunTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/RunTerminal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RunTerminal(ctx, req.(*RunTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetLarkCliConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLarkCliConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetLarkCliConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/GetLarkCliConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetLarkCliConfig(ctx, req.(*GetLarkCliConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_SaveLarkCliConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveLarkCliConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).SaveLarkCliConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/SaveLarkCliConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).SaveLarkCliConfig(ctx, req.(*SaveLarkCliConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListWorkspaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkspacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListWorkspaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/ListWorkspaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListWorkspaces(ctx, req.(*ListWorkspacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/GetWorkspace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetWorkspace(ctx, req.(*GetWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/CreateWorkspace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateWorkspace(ctx, req.(*CreateWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/UpdateWorkspace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateWorkspace(ctx, req.(*UpdateWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_SyncWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).SyncWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/SyncWorkspace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).SyncWorkspace(ctx, req.(*SyncWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/DeleteWorkspace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteWorkspace(ctx, req.(*DeleteWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListManagedAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManagedAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListManagedAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/ListManagedAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListManagedAgents(ctx, req.(*ListManagedAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetManagedAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManagedAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetManagedAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/GetManagedAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetManagedAgent(ctx, req.(*GetManagedAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateManagedAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateManagedAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateManagedAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/CreateManagedAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateManagedAgent(ctx, req.(*CreateManagedAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateManagedAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateManagedAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateManagedAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/UpdateManagedAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateManagedAgent(ctx, req.(*UpdateManagedAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteManagedAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteManagedAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteManagedAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/DeleteManagedAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteManagedAgent(ctx, req.(*DeleteManagedAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListSkillPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListSkillPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.Admin/ListSkillPackages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListSkillPackages(ctx, req.(*ListSkillPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rulego.v1.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSkills",
			Handler:    _Admin_ListSkills_Handler,
		},
		{
			MethodName: "UploadSkill",
			Handler:    _Admin_UploadSkill_Handler,
		},
		{
			MethodName: "ListMcpConfigs",
			Handler:    _Admin_ListMcpConfigs_Handler,
		},
		{
			MethodName: "CreateMcpConfig",
			Handler:    _Admin_CreateMcpConfig_Handler,
		},
		{
			MethodName: "UpdateMcpConfig",
			Handler:    _Admin_UpdateMcpConfig_Handler,
		},
		{
			MethodName: "DeleteMcpConfig",
			Handler:    _Admin_DeleteMcpConfig_Handler,
		},
		{
			MethodName: "TestMcpConfig",
			Handler:    _Admin_TestMcpConfig_Handler,
		},
		{
			MethodName: "ListLlmConfigs",
			Handler:    _Admin_ListLlmConfigs_Handler,
		},
		{
			MethodName: "CreateLlmConfig",
			Handler:    _Admin_CreateLlmConfig_Handler,
		},
		{
			MethodName: "UpdateLlmConfig",
			Handler:    _Admin_UpdateLlmConfig_Handler,
		},
		{
			MethodName: "DeleteLlmConfig",
			Handler:    _Admin_DeleteLlmConfig_Handler,
		},
		{
			MethodName: "CreateLlmModelEntry",
			Handler:    _Admin_CreateLlmModelEntry_Handler,
		},
		{
			MethodName: "UpdateLlmModelEntry",
			Handler:    _Admin_UpdateLlmModelEntry_Handler,
		},
		{
			MethodName: "DeleteLlmModelEntry",
			Handler:    _Admin_DeleteLlmModelEntry_Handler,
		},
		{
			MethodName: "RunTerminal",
			Handler:    _Admin_RunTerminal_Handler,
		},
		{
			MethodName: "GetLarkCliConfig",
			Handler:    _Admin_GetLarkCliConfig_Handler,
		},
		{
			MethodName: "SaveLarkCliConfig",
			Handler:    _Admin_SaveLarkCliConfig_Handler,
		},
		{
			MethodName: "ListWorkspaces",
			Handler:    _Admin_ListWorkspaces_Handler,
		},
		{
			MethodName: "GetWorkspace",
			Handler:    _Admin_GetWorkspace_Handler,
		},
		{
			MethodName: "CreateWorkspace",
			Handler:    _Admin_CreateWorkspace_Handler,
		},
		{
			MethodName: "UpdateWorkspace",
			Handler:    _Admin_UpdateWorkspace_Handler,
		},
		{
			MethodName: "SyncWorkspace",
			Handler:    _Admin_SyncWorkspace_Handler,
		},
		{
			MethodName: "DeleteWorkspace",
			Handler:    _Admin_DeleteWorkspace_Handler,
		},
		{
			MethodName: "ListManagedAgents",
			Handler:    _Admin_ListManagedAgents_Handler,
		},
		{
			MethodName: "GetManagedAgent",
			Handler:    _Admin_GetManagedAgent_Handler,
		},
		{
			MethodName: "CreateManagedAgent",
			Handler:    _Admin_CreateManagedAgent_Handler,
		},
		{
			MethodName: "UpdateManagedAgent",
			Handler:    _Admin_UpdateManagedAgent_Handler,
		},
		{
			MethodName: "DeleteManagedAgent",
			Handler:    _Admin_DeleteManagedAgent_Handler,
		},
		{
			MethodName: "ListSkillPackages",
			Handler:    _Admin_ListSkillPackages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rulego/v1/admin.proto",
}
