// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/rulego/v1/admin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Admin_ListSkills_FullMethodName      = "/rulego.v1.Admin/ListSkills"
	Admin_UploadSkill_FullMethodName     = "/rulego.v1.Admin/UploadSkill"
	Admin_ListMcpConfigs_FullMethodName  = "/rulego.v1.Admin/ListMcpConfigs"
	Admin_CreateMcpConfig_FullMethodName = "/rulego.v1.Admin/CreateMcpConfig"
	Admin_UpdateMcpConfig_FullMethodName = "/rulego.v1.Admin/UpdateMcpConfig"
	Admin_DeleteMcpConfig_FullMethodName = "/rulego.v1.Admin/DeleteMcpConfig"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsReply, error)
	UploadSkill(ctx context.Context, in *UploadSkillRequest, opts ...grpc.CallOption) (*UploadSkillReply, error)
	ListMcpConfigs(ctx context.Context, in *ListMcpConfigsRequest, opts ...grpc.CallOption) (*ListMcpConfigsReply, error)
	CreateMcpConfig(ctx context.Context, in *CreateMcpConfigRequest, opts ...grpc.CallOption) (*McpConfigItem, error)
	UpdateMcpConfig(ctx context.Context, in *UpdateMcpConfigRequest, opts ...grpc.CallOption) (*UpdateMcpConfigReply, error)
	DeleteMcpConfig(ctx context.Context, in *DeleteMcpConfigRequest, opts ...grpc.CallOption) (*DeleteMcpConfigReply, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillsReply)
	err := c.cc.Invoke(ctx, Admin_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UploadSkill(ctx context.Context, in *UploadSkillRequest, opts ...grpc.CallOption) (*UploadSkillReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSkillReply)
	err := c.cc.Invoke(ctx, Admin_UploadSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListMcpConfigs(ctx context.Context, in *ListMcpConfigsRequest, opts ...grpc.CallOption) (*ListMcpConfigsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMcpConfigsReply)
	err := c.cc.Invoke(ctx, Admin_ListMcpConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateMcpConfig(ctx context.Context, in *CreateMcpConfigRequest, opts ...grpc.CallOption) (*McpConfigItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpConfigItem)
	err := c.cc.Invoke(ctx, Admin_CreateMcpConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateMcpConfig(ctx context.Context, in *UpdateMcpConfigRequest, opts ...grpc.CallOption) (*UpdateMcpConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMcpConfigReply)
	err := c.cc.Invoke(ctx, Admin_UpdateMcpConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteMcpConfig(ctx context.Context, in *DeleteMcpConfigRequest, opts ...grpc.CallOption) (*DeleteMcpConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMcpConfigReply)
	err := c.cc.Invoke(ctx, Admin_DeleteMcpConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility.
type AdminServer interface {
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsReply, error)
	UploadSkill(context.Context, *UploadSkillRequest) (*UploadSkillReply, error)
	ListMcpConfigs(context.Context, *ListMcpConfigsRequest) (*ListMcpConfigsReply, error)
	CreateMcpConfig(context.Context, *CreateMcpConfigRequest) (*McpConfigItem, error)
	UpdateMcpConfig(context.Context, *UpdateMcpConfigRequest) (*UpdateMcpConfigReply, error)
	DeleteMcpConfig(context.Context, *DeleteMcpConfigRequest) (*DeleteMcpConfigReply, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServer struct{}

func (UnimplementedAdminServer) ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedAdminServer) UploadSkill(context.Context, *UploadSkillRequest) (*UploadSkillReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadSkill not implemented")
}
func (UnimplementedAdminServer) ListMcpConfigs(context.Context, *ListMcpConfigsRequest) (*ListMcpConfigsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMcpConfigs not implemented")
}
func (UnimplementedAdminServer) CreateMcpConfig(context.Context, *CreateMcpConfigRequest) (*McpConfigItem, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMcpConfig not implemented")
}
func (UnimplementedAdminServer) UpdateMcpConfig(context.Context, *UpdateMcpConfigRequest) (*UpdateMcpConfigReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMcpConfig not implemented")
}
func (UnimplementedAdminServer) DeleteMcpConfig(context.Context, *DeleteMcpConfigRequest) (*DeleteMcpConfigReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMcpConfig not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}
func (UnimplementedAdminServer) testEmbeddedByValue()               {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	// If the following call panics, it indicates UnimplementedAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListSkills(ctx, req.(*ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UploadSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UploadSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UploadSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UploadSkill(ctx, req.(*UploadSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListMcpConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMcpConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListMcpConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListMcpConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListMcpConfigs(ctx, req.(*ListMcpConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateMcpConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMcpConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateMcpConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_CreateMcpConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateMcpConfig(ctx, req.(*CreateMcpConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateMcpConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMcpConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateMcpConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateMcpConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateMcpConfig(ctx, req.(*UpdateMcpConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteMcpConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMcpConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteMcpConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeleteMcpConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteMcpConfig(ctx, req.(*DeleteMcpConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rulego.v1.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSkills",
			Handler:    _Admin_ListSkills_Handler,
		},
		{
			MethodName: "UploadSkill",
			Handler:    _Admin_UploadSkill_Handler,
		},
		{
			MethodName: "ListMcpConfigs",
			Handler:    _Admin_ListMcpConfigs_Handler,
		},
		{
			MethodName: "CreateMcpConfig",
			Handler:    _Admin_CreateMcpConfig_Handler,
		},
		{
			MethodName: "UpdateMcpConfig",
			Handler:    _Admin_UpdateMcpConfig_Handler,
		},
		{
			MethodName: "DeleteMcpConfig",
			Handler:    _Admin_DeleteMcpConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rulego/v1/admin.proto",
}
