// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/rulego/v1/chat.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ChatStreamReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ChatStreamReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChatStreamReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ChatStreamReqMultiError, or
// nil if none found.
func (m *ChatStreamReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ChatStreamReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Model

	for idx, item := range m.GetHistory() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChatStreamReqValidationError{
						field:  fmt.Sprintf("History[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChatStreamReqValidationError{
						field:  fmt.Sprintf("History[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChatStreamReqValidationError{
					field:  fmt.Sprintf("History[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for LlmConfigId

	// no validation rules for LlmModelEntryId

	for idx, item := range m.GetAttachments() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChatStreamReqValidationError{
						field:  fmt.Sprintf("Attachments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChatStreamReqValidationError{
						field:  fmt.Sprintf("Attachments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChatStreamReqValidationError{
					field:  fmt.Sprintf("Attachments[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for ManagedAgentId

	if len(errors) > 0 {
		return ChatStreamReqMultiError(errors)
	}

	return nil
}

// ChatStreamReqMultiError is an error wrapping multiple validation errors
// returned by ChatStreamReq.ValidateAll() if the designated constraints
// aren't met.
type ChatStreamReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChatStreamReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChatStreamReqMultiError) AllErrors() []error { return m }

// ChatStreamReqValidationError is the validation error returned by
// ChatStreamReq.Validate if the designated constraints aren't met.
type ChatStreamReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChatStreamReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChatStreamReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChatStreamReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChatStreamReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChatStreamReqValidationError) ErrorName() string { return "ChatStreamReqValidationError" }

// Error satisfies the builtin error interface
func (e ChatStreamReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChatStreamReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChatStreamReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChatStreamReqValidationError{}

// Validate checks the field values on ChatAttachment with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ChatAttachment) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChatAttachment with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ChatAttachmentMultiError,
// or nil if none found.
func (m *ChatAttachment) ValidateAll() error {
	return m.validate(true)
}

func (m *ChatAttachment) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Filename

	// no validation rules for MimeType

	// no validation rules for Text

	// no validation rules for ContentBase64

	if len(errors) > 0 {
		return ChatAttachmentMultiError(errors)
	}

	return nil
}

// ChatAttachmentMultiError is an error wrapping multiple validation errors
// returned by ChatAttachment.ValidateAll() if the designated constraints
// aren't met.
type ChatAttachmentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChatAttachmentMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChatAttachmentMultiError) AllErrors() []error { return m }

// ChatAttachmentValidationError is the validation error returned by
// ChatAttachment.Validate if the designated constraints aren't met.
type ChatAttachmentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChatAttachmentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChatAttachmentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChatAttachmentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChatAttachmentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChatAttachmentValidationError) ErrorName() string { return "ChatAttachmentValidationError" }

// Error satisfies the builtin error interface
func (e ChatAttachmentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChatAttachment.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChatAttachmentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChatAttachmentValidationError{}

// Validate checks the field values on ChatMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ChatMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChatMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ChatMessageMultiError, or
// nil if none found.
func (m *ChatMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *ChatMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Role

	// no validation rules for Content

	if len(errors) > 0 {
		return ChatMessageMultiError(errors)
	}

	return nil
}

// ChatMessageMultiError is an error wrapping multiple validation errors
// returned by ChatMessage.ValidateAll() if the designated constraints aren't met.
type ChatMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChatMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChatMessageMultiError) AllErrors() []error { return m }

// ChatMessageValidationError is the validation error returned by
// ChatMessage.Validate if the designated constraints aren't met.
type ChatMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChatMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChatMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChatMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChatMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChatMessageValidationError) ErrorName() string { return "ChatMessageValidationError" }

// Error satisfies the builtin error interface
func (e ChatMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChatMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChatMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChatMessageValidationError{}

// Validate checks the field values on ChatStreamReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ChatStreamReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChatStreamReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ChatStreamReplyMultiError, or nil if none found.
func (m *ChatStreamReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ChatStreamReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Content

	// no validation rules for Done

	// no validation rules for Error

	if len(errors) > 0 {
		return ChatStreamReplyMultiError(errors)
	}

	return nil
}

// ChatStreamReplyMultiError is an error wrapping multiple validation errors
// returned by ChatStreamReply.ValidateAll() if the designated constraints
// aren't met.
type ChatStreamReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChatStreamReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChatStreamReplyMultiError) AllErrors() []error { return m }

// ChatStreamReplyValidationError is the validation error returned by
// ChatStreamReply.Validate if the designated constraints aren't met.
type ChatStreamReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChatStreamReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChatStreamReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChatStreamReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChatStreamReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChatStreamReplyValidationError) ErrorName() string { return "ChatStreamReplyValidationError" }

// Error satisfies the builtin error interface
func (e ChatStreamReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChatStreamReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChatStreamReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChatStreamReplyValidationError{}
