// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: api/rulego/v1/chat.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationChatRuleChainTest = "/rulego.v1.Chat/RuleChainTest"

type ChatHTTPServer interface {
	RuleChainTest(context.Context, *RuleChainTestReq) (*RuleChainTestReply, error)
}

func RegisterChatHTTPServer(s *http.Server, srv ChatHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/chat/rule-chain-test", _Chat_RuleChainTest0_HTTP_Handler(srv))
}

func _Chat_RuleChainTest0_HTTP_Handler(srv ChatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RuleChainTestReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatRuleChainTest)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RuleChainTest(ctx, req.(*RuleChainTestReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RuleChainTestReply)
		return ctx.Result(200, reply)
	}
}

type ChatHTTPClient interface {
	RuleChainTest(ctx context.Context, req *RuleChainTestReq, opts ...http.CallOption) (rsp *RuleChainTestReply, err error)
}

type ChatHTTPClientImpl struct {
	cc *http.Client
}

func NewChatHTTPClient(client *http.Client) ChatHTTPClient {
	return &ChatHTTPClientImpl{client}
}

func (c *ChatHTTPClientImpl) RuleChainTest(ctx context.Context, in *RuleChainTestReq, opts ...http.CallOption) (*RuleChainTestReply, error) {
	var out RuleChainTestReply
	pattern := "/api/v1/chat/rule-chain-test"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChatRuleChainTest))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
