// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/rulego/v1/chat.proto

package v1

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatStreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 用户消息
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`     // 模型名称，可选，默认使用配置中的模型
	History       []*ChatMessage         `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"` // 对话历史
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamReq) Reset() {
	*x = ChatStreamReq{}
	mi := &file_api_rulego_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamReq) ProtoMessage() {}

func (x *ChatStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_rulego_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamReq.ProtoReflect.Descriptor instead.
func (*ChatStreamReq) Descriptor() ([]byte, []int) {
	return file_api_rulego_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatStreamReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatStreamReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatStreamReq) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`       // "user" 或 "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_api_rulego_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_rulego_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_api_rulego_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatStreamReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"` // 流式返回的内容片段
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`      // 是否完成
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`     // 错误信息（如果有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamReply) Reset() {
	*x = ChatStreamReply{}
	mi := &file_api_rulego_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamReply) ProtoMessage() {}

func (x *ChatStreamReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_rulego_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamReply.ProtoReflect.Descriptor instead.
func (*ChatStreamReply) Descriptor() ([]byte, []int) {
	return file_api_rulego_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatStreamReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatStreamReply) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatStreamReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_rulego_v1_chat_proto protoreflect.FileDescriptor

const file_api_rulego_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x18api/rulego/v1/chat.proto\x12\trulego.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1copenapi/v3/annotations.proto\"q\n" +
	"\rChatStreamReq\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x120\n" +
	"\ahistory\x18\x03 \x03(\v2\x16.rulego.v1.ChatMessageR\ahistory\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"U\n" +
	"\x0fChatStreamReply\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xde\x01\n" +
	"\x04Chat\x12\xd5\x01\n" +
	"\n" +
	"ChatStream\x12\x18.rulego.v1.ChatStreamReq\x1a\x1a.rulego.v1.ChatStreamReply\"\x8e\x01\xbaGm\n" +
	"\x04Chat\x12\x18与大模型流式对话\x1a?使用Server-Sent Events (SSE)实现与大模型的流式对话*\n" +
	"ChatStream\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/chat/stream0\x01B\x1fZ\x1druleGoKratos/api/rulego/v1;v1b\x06proto3"

var (
	file_api_rulego_v1_chat_proto_rawDescOnce sync.Once
	file_api_rulego_v1_chat_proto_rawDescData []byte
)

func file_api_rulego_v1_chat_proto_rawDescGZIP() []byte {
	file_api_rulego_v1_chat_proto_rawDescOnce.Do(func() {
		file_api_rulego_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rulego_v1_chat_proto_rawDesc), len(file_api_rulego_v1_chat_proto_rawDesc)))
	})
	return file_api_rulego_v1_chat_proto_rawDescData
}

var file_api_rulego_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_rulego_v1_chat_proto_goTypes = []any{
	(*ChatStreamReq)(nil),   // 0: rulego.v1.ChatStreamReq
	(*ChatMessage)(nil),     // 1: rulego.v1.ChatMessage
	(*ChatStreamReply)(nil), // 2: rulego.v1.ChatStreamReply
}
var file_api_rulego_v1_chat_proto_depIdxs = []int32{
	1, // 0: rulego.v1.ChatStreamReq.history:type_name -> rulego.v1.ChatMessage
	0, // 1: rulego.v1.Chat.ChatStream:input_type -> rulego.v1.ChatStreamReq
	2, // 2: rulego.v1.Chat.ChatStream:output_type -> rulego.v1.ChatStreamReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_rulego_v1_chat_proto_init() }
func file_api_rulego_v1_chat_proto_init() {
	if File_api_rulego_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rulego_v1_chat_proto_rawDesc), len(file_api_rulego_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rulego_v1_chat_proto_goTypes,
		DependencyIndexes: file_api_rulego_v1_chat_proto_depIdxs,
		MessageInfos:      file_api_rulego_v1_chat_proto_msgTypes,
	}.Build()
	File_api_rulego_v1_chat_proto = out.File
	file_api_rulego_v1_chat_proto_goTypes = nil
	file_api_rulego_v1_chat_proto_depIdxs = nil
}
