// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/rulego/v1/components.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Component_ListComponentUseRule_FullMethodName   = "/rulego.v1.Component/ListComponentUseRule"
	Component_UpdateComponentUseRule_FullMethodName = "/rulego.v1.Component/UpdateComponentUseRule"
	Component_CreateComponentUseRule_FullMethodName = "/rulego.v1.Component/CreateComponentUseRule"
)

// ComponentClient is the client API for Component service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type ComponentClient interface {
	ListComponentUseRule(ctx context.Context, in *ListComponentUseRuleRequest, opts ...grpc.CallOption) (*ListComponentUseRuleReply, error)
	UpdateComponentUseRule(ctx context.Context, in *UpdateComponentUseRuleRequest, opts ...grpc.CallOption) (*UpdateComponentUseRuleReply, error)
	CreateComponentUseRule(ctx context.Context, in *CreateComponentUseRuleRequest, opts ...grpc.CallOption) (*CreateComponentUseRuleReply, error)
}

type componentClient struct {
	cc grpc.ClientConnInterface
}

func NewComponentClient(cc grpc.ClientConnInterface) ComponentClient {
	return &componentClient{cc}
}

func (c *componentClient) ListComponentUseRule(ctx context.Context, in *ListComponentUseRuleRequest, opts ...grpc.CallOption) (*ListComponentUseRuleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListComponentUseRuleReply)
	err := c.cc.Invoke(ctx, Component_ListComponentUseRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *componentClient) UpdateComponentUseRule(ctx context.Context, in *UpdateComponentUseRuleRequest, opts ...grpc.CallOption) (*UpdateComponentUseRuleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateComponentUseRuleReply)
	err := c.cc.Invoke(ctx, Component_UpdateComponentUseRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *componentClient) CreateComponentUseRule(ctx context.Context, in *CreateComponentUseRuleRequest, opts ...grpc.CallOption) (*CreateComponentUseRuleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateComponentUseRuleReply)
	err := c.cc.Invoke(ctx, Component_CreateComponentUseRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComponentServer is the server API for Component service.
// All implementations must embed UnimplementedComponentServer
// for forward compatibility.
//
// The greeting service definition.
type ComponentServer interface {
	ListComponentUseRule(context.Context, *ListComponentUseRuleRequest) (*ListComponentUseRuleReply, error)
	UpdateComponentUseRule(context.Context, *UpdateComponentUseRuleRequest) (*UpdateComponentUseRuleReply, error)
	CreateComponentUseRule(context.Context, *CreateComponentUseRuleRequest) (*CreateComponentUseRuleReply, error)
	mustEmbedUnimplementedComponentServer()
}

// UnimplementedComponentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComponentServer struct{}

func (UnimplementedComponentServer) ListComponentUseRule(context.Context, *ListComponentUseRuleRequest) (*ListComponentUseRuleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComponentUseRule not implemented")
}
func (UnimplementedComponentServer) UpdateComponentUseRule(context.Context, *UpdateComponentUseRuleRequest) (*UpdateComponentUseRuleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateComponentUseRule not implemented")
}
func (UnimplementedComponentServer) CreateComponentUseRule(context.Context, *CreateComponentUseRuleRequest) (*CreateComponentUseRuleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComponentUseRule not implemented")
}
func (UnimplementedComponentServer) mustEmbedUnimplementedComponentServer() {}
func (UnimplementedComponentServer) testEmbeddedByValue()                   {}

// UnsafeComponentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComponentServer will
// result in compilation errors.
type UnsafeComponentServer interface {
	mustEmbedUnimplementedComponentServer()
}

func RegisterComponentServer(s grpc.ServiceRegistrar, srv ComponentServer) {
	// If the following call panics, it indicates UnimplementedComponentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Component_ServiceDesc, srv)
}

func _Component_ListComponentUseRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListComponentUseRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComponentServer).ListComponentUseRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Component_ListComponentUseRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComponentServer).ListComponentUseRule(ctx, req.(*ListComponentUseRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Component_UpdateComponentUseRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateComponentUseRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComponentServer).UpdateComponentUseRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Component_UpdateComponentUseRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComponentServer).UpdateComponentUseRule(ctx, req.(*UpdateComponentUseRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Component_CreateComponentUseRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateComponentUseRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComponentServer).CreateComponentUseRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Component_CreateComponentUseRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComponentServer).CreateComponentUseRule(ctx, req.(*CreateComponentUseRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Component_ServiceDesc is the grpc.ServiceDesc for Component service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Component_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rulego.v1.Component",
	HandlerType: (*ComponentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListComponentUseRule",
			Handler:    _Component_ListComponentUseRule_Handler,
		},
		{
			MethodName: "UpdateComponentUseRule",
			Handler:    _Component_UpdateComponentUseRule_Handler,
		},
		{
			MethodName: "CreateComponentUseRule",
			Handler:    _Component_CreateComponentUseRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rulego/v1/components.proto",
}
