// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: api/rulego/v1/components.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationComponentCreateComponentUseRule = "/rulego.v1.Component/CreateComponentUseRule"
const OperationComponentListComponentUseRule = "/rulego.v1.Component/ListComponentUseRule"
const OperationComponentUpdateComponentUseRule = "/rulego.v1.Component/UpdateComponentUseRule"

type ComponentHTTPServer interface {
	CreateComponentUseRule(context.Context, *CreateComponentUseRuleRequest) (*CreateComponentUseRuleReply, error)
	ListComponentUseRule(context.Context, *ListComponentUseRuleRequest) (*ListComponentUseRuleReply, error)
	UpdateComponentUseRule(context.Context, *UpdateComponentUseRuleRequest) (*UpdateComponentUseRuleReply, error)
}

func RegisterComponentHTTPServer(s *http.Server, srv ComponentHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/componentUseRule/page", _Component_ListComponentUseRule0_HTTP_Handler(srv))
	r.POST("/api/v1/componentUseRule/update", _Component_UpdateComponentUseRule0_HTTP_Handler(srv))
	r.POST("/api/v1/componentUseRule/create", _Component_CreateComponentUseRule0_HTTP_Handler(srv))
}

func _Component_ListComponentUseRule0_HTTP_Handler(srv ComponentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListComponentUseRuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationComponentListComponentUseRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListComponentUseRule(ctx, req.(*ListComponentUseRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListComponentUseRuleReply)
		return ctx.Result(200, reply)
	}
}

func _Component_UpdateComponentUseRule0_HTTP_Handler(srv ComponentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateComponentUseRuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationComponentUpdateComponentUseRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateComponentUseRule(ctx, req.(*UpdateComponentUseRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateComponentUseRuleReply)
		return ctx.Result(200, reply)
	}
}

func _Component_CreateComponentUseRule0_HTTP_Handler(srv ComponentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateComponentUseRuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationComponentCreateComponentUseRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateComponentUseRule(ctx, req.(*CreateComponentUseRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateComponentUseRuleReply)
		return ctx.Result(200, reply)
	}
}

type ComponentHTTPClient interface {
	CreateComponentUseRule(ctx context.Context, req *CreateComponentUseRuleRequest, opts ...http.CallOption) (rsp *CreateComponentUseRuleReply, err error)
	ListComponentUseRule(ctx context.Context, req *ListComponentUseRuleRequest, opts ...http.CallOption) (rsp *ListComponentUseRuleReply, err error)
	UpdateComponentUseRule(ctx context.Context, req *UpdateComponentUseRuleRequest, opts ...http.CallOption) (rsp *UpdateComponentUseRuleReply, err error)
}

type ComponentHTTPClientImpl struct {
	cc *http.Client
}

func NewComponentHTTPClient(client *http.Client) ComponentHTTPClient {
	return &ComponentHTTPClientImpl{client}
}

func (c *ComponentHTTPClientImpl) CreateComponentUseRule(ctx context.Context, in *CreateComponentUseRuleRequest, opts ...http.CallOption) (*CreateComponentUseRuleReply, error) {
	var out CreateComponentUseRuleReply
	pattern := "/api/v1/componentUseRule/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationComponentCreateComponentUseRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ComponentHTTPClientImpl) ListComponentUseRule(ctx context.Context, in *ListComponentUseRuleRequest, opts ...http.CallOption) (*ListComponentUseRuleReply, error) {
	var out ListComponentUseRuleReply
	pattern := "/api/v1/componentUseRule/page"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationComponentListComponentUseRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ComponentHTTPClientImpl) UpdateComponentUseRule(ctx context.Context, in *UpdateComponentUseRuleRequest, opts ...http.CallOption) (*UpdateComponentUseRuleReply, error) {
	var out UpdateComponentUseRuleReply
	pattern := "/api/v1/componentUseRule/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationComponentUpdateComponentUseRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
