// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/rulego/v1/md.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	ChainId       string                 `protobuf:"bytes,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMdRequest) Reset() {
	*x = CreateMdRequest{}
	mi := &file_api_rulego_v1_md_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMdRequest) ProtoMessage() {}

func (x *CreateMdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rulego_v1_md_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMdRequest.ProtoReflect.Descriptor instead.
func (*CreateMdRequest) Descriptor() ([]byte, []int) {
	return file_api_rulego_v1_md_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMdRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMdRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateMdRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateMdRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type UpdateMdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Desc          string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	ChainId       string                 `protobuf:"bytes,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMdRequest) Reset() {
	*x = UpdateMdRequest{}
	mi := &file_api_rulego_v1_md_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMdRequest) ProtoMessage() {}

func (x *UpdateMdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rulego_v1_md_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMdRequest.ProtoReflect.Descriptor instead.
func (*UpdateMdRequest) Descriptor() ([]byte, []int) {
	return file_api_rulego_v1_md_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMdRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateMdRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateMdRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UpdateMdRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type ListMdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMdRequest) Reset() {
	*x = ListMdRequest{}
	mi := &file_api_rulego_v1_md_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMdRequest) ProtoMessage() {}

func (x *ListMdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rulego_v1_md_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMdRequest.ProtoReflect.Descriptor instead.
func (*ListMdRequest) Descriptor() ([]byte, []int) {
	return file_api_rulego_v1_md_proto_rawDescGZIP(), []int{2}
}

func (x *ListMdRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMdRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type MdItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Desc          string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	ChainId       string                 `protobuf:"bytes,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainName     string                 `protobuf:"bytes,6,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	ChainVersion  int32                  `protobuf:"varint,7,opt,name=chain_version,json=chainVersion,proto3" json:"chain_version,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MdItem) Reset() {
	*x = MdItem{}
	mi := &file_api_rulego_v1_md_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MdItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MdItem) ProtoMessage() {}

func (x *MdItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_rulego_v1_md_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MdItem.ProtoReflect.Descriptor instead.
func (*MdItem) Descriptor() ([]byte, []int) {
	return file_api_rulego_v1_md_proto_rawDescGZIP(), []int{3}
}

func (x *MdItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MdItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MdItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MdItem) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *MdItem) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *MdItem) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *MdItem) GetChainVersion() int32 {
	if x != nil {
		return x.ChainVersion
	}
	return 0
}

func (x *MdItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MdItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListMdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MdItem              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMdReply) Reset() {
	*x = ListMdReply{}
	mi := &file_api_rulego_v1_md_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMdReply) ProtoMessage() {}

func (x *ListMdReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_rulego_v1_md_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMdReply.ProtoReflect.Descriptor instead.
func (*ListMdReply) Descriptor() ([]byte, []int) {
	return file_api_rulego_v1_md_proto_rawDescGZIP(), []int{4}
}

func (x *ListMdReply) GetItems() []*MdItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListMdReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMdReply) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListMdReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_rulego_v1_md_proto protoreflect.FileDescriptor

const file_api_rulego_v1_md_proto_rawDesc = "" +
	"\n" +
	"\x16api/rulego/v1/md.proto\x12\trulego.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17validate/validate.proto\"p\n" +
	"\x0fCreateMdRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x19\n" +
	"\bchain_id\x18\x04 \x01(\tR\achainId\"\x80\x01\n" +
	"\x0fUpdateMdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x19\n" +
	"\bchain_id\x18\x05 \x01(\tR\achainId\"7\n" +
	"\rListMdRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\xf9\x01\n" +
	"\x06MdItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x19\n" +
	"\bchain_id\x18\x05 \x01(\tR\achainId\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x06 \x01(\tR\tchainName\x12#\n" +
	"\rchain_version\x18\a \x01(\x05R\fchainVersion\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"t\n" +
	"\vListMdReply\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.rulego.v1.MdItemR\x05items\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total2\x8e\x02\n" +
	"\n" +
	"MdWorkflow\x12R\n" +
	"\x04List\x12\x18.rulego.v1.ListMdRequest\x1a\x16.rulego.v1.ListMdReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/doc/list\x12T\n" +
	"\x06Update\x12\x1a.rulego.v1.UpdateMdRequest\x1a\x11.rulego.v1.MdItem\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/doc/edit\x12V\n" +
	"\x06Create\x12\x1a.rulego.v1.CreateMdRequest\x1a\x11.rulego.v1.MdItem\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/doc/createB\x1fZ\x1druleGoKratos/api/rulego/v1;v1b\x06proto3"

var (
	file_api_rulego_v1_md_proto_rawDescOnce sync.Once
	file_api_rulego_v1_md_proto_rawDescData []byte
)

func file_api_rulego_v1_md_proto_rawDescGZIP() []byte {
	file_api_rulego_v1_md_proto_rawDescOnce.Do(func() {
		file_api_rulego_v1_md_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rulego_v1_md_proto_rawDesc), len(file_api_rulego_v1_md_proto_rawDesc)))
	})
	return file_api_rulego_v1_md_proto_rawDescData
}

var file_api_rulego_v1_md_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_rulego_v1_md_proto_goTypes = []any{
	(*CreateMdRequest)(nil), // 0: rulego.v1.CreateMdRequest
	(*UpdateMdRequest)(nil), // 1: rulego.v1.UpdateMdRequest
	(*ListMdRequest)(nil),   // 2: rulego.v1.ListMdRequest
	(*MdItem)(nil),          // 3: rulego.v1.MdItem
	(*ListMdReply)(nil),     // 4: rulego.v1.ListMdReply
}
var file_api_rulego_v1_md_proto_depIdxs = []int32{
	3, // 0: rulego.v1.ListMdReply.items:type_name -> rulego.v1.MdItem
	2, // 1: rulego.v1.MdWorkflow.List:input_type -> rulego.v1.ListMdRequest
	1, // 2: rulego.v1.MdWorkflow.Update:input_type -> rulego.v1.UpdateMdRequest
	0, // 3: rulego.v1.MdWorkflow.Create:input_type -> rulego.v1.CreateMdRequest
	4, // 4: rulego.v1.MdWorkflow.List:output_type -> rulego.v1.ListMdReply
	3, // 5: rulego.v1.MdWorkflow.Update:output_type -> rulego.v1.MdItem
	3, // 6: rulego.v1.MdWorkflow.Create:output_type -> rulego.v1.MdItem
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_rulego_v1_md_proto_init() }
func file_api_rulego_v1_md_proto_init() {
	if File_api_rulego_v1_md_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rulego_v1_md_proto_rawDesc), len(file_api_rulego_v1_md_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rulego_v1_md_proto_goTypes,
		DependencyIndexes: file_api_rulego_v1_md_proto_depIdxs,
		MessageInfos:      file_api_rulego_v1_md_proto_msgTypes,
	}.Build()
	File_api_rulego_v1_md_proto = out.File
	file_api_rulego_v1_md_proto_goTypes = nil
	file_api_rulego_v1_md_proto_depIdxs = nil
}
