// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.21.12
// source: api/rulego/v1/md.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMdWorkflowCreate = "/rulego.v1.MdWorkflow/Create"
const OperationMdWorkflowList = "/rulego.v1.MdWorkflow/List"
const OperationMdWorkflowUpdate = "/rulego.v1.MdWorkflow/Update"

type MdWorkflowHTTPServer interface {
	Create(context.Context, *CreateMdRequest) (*MdItem, error)
	List(context.Context, *ListMdRequest) (*ListMdReply, error)
	Update(context.Context, *UpdateMdRequest) (*MdItem, error)
}

func RegisterMdWorkflowHTTPServer(s *http.Server, srv MdWorkflowHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/doc/list", _MdWorkflow_List0_HTTP_Handler(srv))
	r.POST("/api/v1/doc/edit", _MdWorkflow_Update0_HTTP_Handler(srv))
	r.POST("/api/v1/doc/create", _MdWorkflow_Create0_HTTP_Handler(srv))
}

func _MdWorkflow_List0_HTTP_Handler(srv MdWorkflowHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMdWorkflowList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*ListMdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMdReply)
		return ctx.Result(200, reply)
	}
}

func _MdWorkflow_Update0_HTTP_Handler(srv MdWorkflowHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateMdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMdWorkflowUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*UpdateMdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MdItem)
		return ctx.Result(200, reply)
	}
}

func _MdWorkflow_Create0_HTTP_Handler(srv MdWorkflowHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateMdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMdWorkflowCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*CreateMdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MdItem)
		return ctx.Result(200, reply)
	}
}

type MdWorkflowHTTPClient interface {
	Create(ctx context.Context, req *CreateMdRequest, opts ...http.CallOption) (rsp *MdItem, err error)
	List(ctx context.Context, req *ListMdRequest, opts ...http.CallOption) (rsp *ListMdReply, err error)
	Update(ctx context.Context, req *UpdateMdRequest, opts ...http.CallOption) (rsp *MdItem, err error)
}

type MdWorkflowHTTPClientImpl struct {
	cc *http.Client
}

func NewMdWorkflowHTTPClient(client *http.Client) MdWorkflowHTTPClient {
	return &MdWorkflowHTTPClientImpl{client}
}

func (c *MdWorkflowHTTPClientImpl) Create(ctx context.Context, in *CreateMdRequest, opts ...http.CallOption) (*MdItem, error) {
	var out MdItem
	pattern := "/api/v1/doc/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMdWorkflowCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MdWorkflowHTTPClientImpl) List(ctx context.Context, in *ListMdRequest, opts ...http.CallOption) (*ListMdReply, error) {
	var out ListMdReply
	pattern := "/api/v1/doc/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMdWorkflowList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MdWorkflowHTTPClientImpl) Update(ctx context.Context, in *UpdateMdRequest, opts ...http.CallOption) (*MdItem, error) {
	var out MdItem
	pattern := "/api/v1/doc/edit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMdWorkflowUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
