// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/rulego/v1/rules.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RuleGoClient is the client API for RuleGo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuleGoClient interface {
	// 获取所有组件
	GetComponents(ctx context.Context, in *GetComponentsReq, opts ...grpc.CallOption) (*GetComponentsReply, error)
	// 获取所有规则链列表
	GetRegulationsList(ctx context.Context, in *GetRegulationsListReq, opts ...grpc.CallOption) (*GetRegulationsListReply, error)
}

type ruleGoClient struct {
	cc grpc.ClientConnInterface
}

func NewRuleGoClient(cc grpc.ClientConnInterface) RuleGoClient {
	return &ruleGoClient{cc}
}

func (c *ruleGoClient) GetComponents(ctx context.Context, in *GetComponentsReq, opts ...grpc.CallOption) (*GetComponentsReply, error) {
	out := new(GetComponentsReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.RuleGo/GetComponents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleGoClient) GetRegulationsList(ctx context.Context, in *GetRegulationsListReq, opts ...grpc.CallOption) (*GetRegulationsListReply, error) {
	out := new(GetRegulationsListReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.RuleGo/GetRegulationsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleGoServer is the server API for RuleGo service.
// All implementations must embed UnimplementedRuleGoServer
// for forward compatibility
type RuleGoServer interface {
	// 获取所有组件
	GetComponents(context.Context, *GetComponentsReq) (*GetComponentsReply, error)
	// 获取所有规则链列表
	GetRegulationsList(context.Context, *GetRegulationsListReq) (*GetRegulationsListReply, error)
	mustEmbedUnimplementedRuleGoServer()
}

// UnimplementedRuleGoServer must be embedded to have forward compatible implementations.
type UnimplementedRuleGoServer struct {
}

func (UnimplementedRuleGoServer) GetComponents(context.Context, *GetComponentsReq) (*GetComponentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComponents not implemented")
}
func (UnimplementedRuleGoServer) GetRegulationsList(context.Context, *GetRegulationsListReq) (*GetRegulationsListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegulationsList not implemented")
}
func (UnimplementedRuleGoServer) mustEmbedUnimplementedRuleGoServer() {}

// UnsafeRuleGoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuleGoServer will
// result in compilation errors.
type UnsafeRuleGoServer interface {
	mustEmbedUnimplementedRuleGoServer()
}

func RegisterRuleGoServer(s grpc.ServiceRegistrar, srv RuleGoServer) {
	s.RegisterService(&RuleGo_ServiceDesc, srv)
}

func _RuleGo_GetComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComponentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleGoServer).GetComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.RuleGo/GetComponents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleGoServer).GetComponents(ctx, req.(*GetComponentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleGo_GetRegulationsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegulationsListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleGoServer).GetRegulationsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.RuleGo/GetRegulationsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleGoServer).GetRegulationsList(ctx, req.(*GetRegulationsListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RuleGo_ServiceDesc is the grpc.ServiceDesc for RuleGo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuleGo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rulego.v1.RuleGo",
	HandlerType: (*RuleGoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetComponents",
			Handler:    _RuleGo_GetComponents_Handler,
		},
		{
			MethodName: "GetRegulationsList",
			Handler:    _RuleGo_GetRegulationsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rulego/v1/rules.proto",
}
