// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/rulego/v1/rules.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetComponentsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetComponentsReq) Reset() {
	*x = GetComponentsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rulego_v1_rules_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetComponentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComponentsReq) ProtoMessage() {}

func (x *GetComponentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_rulego_v1_rules_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComponentsReq.ProtoReflect.Descriptor instead.
func (*GetComponentsReq) Descriptor() ([]byte, []int) {
	return file_api_rulego_v1_rules_proto_rawDescGZIP(), []int{0}
}

type GetComponentsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoints *structpb.ListValue `protobuf:"bytes,1,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	Nodes     *structpb.ListValue `protobuf:"bytes,2,opt,name=nodes,proto3" json:"nodes,omitempty"`
	Builtins  *structpb.Struct    `protobuf:"bytes,3,opt,name=builtins,proto3" json:"builtins,omitempty"`
}

func (x *GetComponentsReply) Reset() {
	*x = GetComponentsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rulego_v1_rules_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetComponentsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComponentsReply) ProtoMessage() {}

func (x *GetComponentsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_rulego_v1_rules_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComponentsReply.ProtoReflect.Descriptor instead.
func (*GetComponentsReply) Descriptor() ([]byte, []int) {
	return file_api_rulego_v1_rules_proto_rawDescGZIP(), []int{1}
}

func (x *GetComponentsReply) GetEndpoints() *structpb.ListValue {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *GetComponentsReply) GetNodes() *structpb.ListValue {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetComponentsReply) GetBuiltins() *structpb.Struct {
	if x != nil {
		return x.Builtins
	}
	return nil
}

var File_api_rulego_v1_rules_proto protoreflect.FileDescriptor

var file_api_rulego_v1_rules_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x75, 0x6c, 0x65, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x75, 0x6c,
	0x65, 0x67, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x22, 0xb5, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x38, 0x0a,
	0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x65, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x33, 0x0a, 0x08, 0x62, 0x75, 0x69,
	0x6c, 0x74, 0x69, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x52, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x73, 0x32, 0x71,
	0x0a, 0x06, 0x52, 0x75, 0x6c, 0x65, 0x47, 0x6f, 0x12, 0x67, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1b, 0x2e, 0x72, 0x75, 0x6c, 0x65,
	0x67, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x72, 0x75, 0x6c, 0x65, 0x67, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x42, 0x1f, 0x5a, 0x1d, 0x72, 0x75, 0x6c, 0x65, 0x47, 0x6f, 0x4b, 0x72, 0x61, 0x74, 0x6f,
	0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x75, 0x6c, 0x65, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_rulego_v1_rules_proto_rawDescOnce sync.Once
	file_api_rulego_v1_rules_proto_rawDescData = file_api_rulego_v1_rules_proto_rawDesc
)

func file_api_rulego_v1_rules_proto_rawDescGZIP() []byte {
	file_api_rulego_v1_rules_proto_rawDescOnce.Do(func() {
		file_api_rulego_v1_rules_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_rulego_v1_rules_proto_rawDescData)
	})
	return file_api_rulego_v1_rules_proto_rawDescData
}

var file_api_rulego_v1_rules_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_rulego_v1_rules_proto_goTypes = []interface{}{
	(*GetComponentsReq)(nil),   // 0: rulego.v1.GetComponentsReq
	(*GetComponentsReply)(nil), // 1: rulego.v1.GetComponentsReply
	(*structpb.ListValue)(nil), // 2: google.protobuf.ListValue
	(*structpb.Struct)(nil),    // 3: google.protobuf.Struct
}
var file_api_rulego_v1_rules_proto_depIdxs = []int32{
	2, // 0: rulego.v1.GetComponentsReply.endpoints:type_name -> google.protobuf.ListValue
	2, // 1: rulego.v1.GetComponentsReply.nodes:type_name -> google.protobuf.ListValue
	3, // 2: rulego.v1.GetComponentsReply.builtins:type_name -> google.protobuf.Struct
	0, // 3: rulego.v1.RuleGo.GetComponents:input_type -> rulego.v1.GetComponentsReq
	1, // 4: rulego.v1.RuleGo.GetComponents:output_type -> rulego.v1.GetComponentsReply
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_rulego_v1_rules_proto_init() }
func file_api_rulego_v1_rules_proto_init() {
	if File_api_rulego_v1_rules_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_rulego_v1_rules_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetComponentsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rulego_v1_rules_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetComponentsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_rulego_v1_rules_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rulego_v1_rules_proto_goTypes,
		DependencyIndexes: file_api_rulego_v1_rules_proto_depIdxs,
		MessageInfos:      file_api_rulego_v1_rules_proto_msgTypes,
	}.Build()
	File_api_rulego_v1_rules_proto = out.File
	file_api_rulego_v1_rules_proto_rawDesc = nil
	file_api_rulego_v1_rules_proto_goTypes = nil
	file_api_rulego_v1_rules_proto_depIdxs = nil
}
