syntax = "proto3";

package rulego.v1;

import "google/api/annotations.proto";
import "google/protobuf/struct.proto";

option go_package = "ruleGoKratos/api/rulego/v1;v1";


// The greeting service definition.
service RuleGo {
  
  // 获取所有组件
  rpc GetComponents(GetComponentsReq) returns(GetComponentsReply) {
    option (google.api.http) = {
      get: "/api/v1/components"
    };
  }
}



message GetComponentsReq {}

message GetComponentsReply {
	google.protobuf.ListValue endpoints = 1;
	google.protobuf.ListValue nodes = 2;
	google.protobuf.Struct builtins = 3;
}

