syntax = "proto3";

package rulego.v1;

import "google/api/annotations.proto";
import "google/protobuf/struct.proto";

option go_package = "ruleGoKratos/api/rulego/v1;v1";


// The greeting service definition.
service RuleGo {
  
  // 获取所有组件
  rpc GetComponents(GetComponentsReq) returns(GetComponentsReply) {
    option (google.api.http) = {
      get: "/api/v1/components"
    };
  }

  // 获取所有规则链列表
  rpc GetRegulationsList(GetRegulationsListReq) returns(GetRegulationsListReply) {
    option (google.api.http) = {
      get: "/api/v1/rules"
    };
  }
}



message GetComponentsReq {}

message GetComponentsReply {
	google.protobuf.ListValue endpoints = 1;
	google.protobuf.ListValue nodes = 2;
	google.protobuf.Struct builtins = 3;
}

message GetRegulationsListReq {
  string page = 1;
  string size = 2;
  string keywords = 3;
  string root = 4;
  string disabled = 5;
}

message GetRegulationsListReply {
	repeated google.protobuf.Struct items = 1;
  int32 total = 2;
  int32 page = 3;
  int32 size = 4;
}
