// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/rulego/v1/rules.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RuleGoClient is the client API for RuleGo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuleGoClient interface {
	// 获取所有组件
	GetComponents(ctx context.Context, in *GetComponentsReq, opts ...grpc.CallOption) (*GetComponentsReply, error)
	// 获取所有规则链列表
	GetRegulationsList(ctx context.Context, in *GetRegulationsListReq, opts ...grpc.CallOption) (*GetRegulationsListReply, error)
	// 获取单个规则链
	GetRuleChain(ctx context.Context, in *GetRuleChainReq, opts ...grpc.CallOption) (*GetRuleChainReply, error)
	// 异步执行规则链
	ExecuteRuleChain(ctx context.Context, in *ExecuteRuleChainReq, opts ...grpc.CallOption) (*ExecuteRuleChainReply, error)
	// 同步执行规则链
	ExecuteRuleChainSync(ctx context.Context, in *ExecuteRuleChainReq, opts ...grpc.CallOption) (*ExecuteRuleChainSyncReply, error)
	// 部署或者下线规则链
	DeployRuleChain(ctx context.Context, in *DeployRuleChainReq, opts ...grpc.CallOption) (*DeployRuleChainReply, error)
	// 新增或修改规则链
	UpsertRuleChain(ctx context.Context, in *UpsertRuleChainReq, opts ...grpc.CallOption) (*UpsertRuleChainReply, error)
	// 保存规则链附加信息
	UpdateRuleChainBaseInfo(ctx context.Context, in *UpdateRuleChainBaseInfoReq, opts ...grpc.CallOption) (*UpdateRuleChainBaseInfoReply, error)
}

type ruleGoClient struct {
	cc grpc.ClientConnInterface
}

func NewRuleGoClient(cc grpc.ClientConnInterface) RuleGoClient {
	return &ruleGoClient{cc}
}

func (c *ruleGoClient) GetComponents(ctx context.Context, in *GetComponentsReq, opts ...grpc.CallOption) (*GetComponentsReply, error) {
	out := new(GetComponentsReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.RuleGo/GetComponents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleGoClient) GetRegulationsList(ctx context.Context, in *GetRegulationsListReq, opts ...grpc.CallOption) (*GetRegulationsListReply, error) {
	out := new(GetRegulationsListReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.RuleGo/GetRegulationsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleGoClient) GetRuleChain(ctx context.Context, in *GetRuleChainReq, opts ...grpc.CallOption) (*GetRuleChainReply, error) {
	out := new(GetRuleChainReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.RuleGo/GetRuleChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleGoClient) ExecuteRuleChain(ctx context.Context, in *ExecuteRuleChainReq, opts ...grpc.CallOption) (*ExecuteRuleChainReply, error) {
	out := new(ExecuteRuleChainReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.RuleGo/ExecuteRuleChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleGoClient) ExecuteRuleChainSync(ctx context.Context, in *ExecuteRuleChainReq, opts ...grpc.CallOption) (*ExecuteRuleChainSyncReply, error) {
	out := new(ExecuteRuleChainSyncReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.RuleGo/ExecuteRuleChainSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleGoClient) DeployRuleChain(ctx context.Context, in *DeployRuleChainReq, opts ...grpc.CallOption) (*DeployRuleChainReply, error) {
	out := new(DeployRuleChainReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.RuleGo/DeployRuleChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleGoClient) UpsertRuleChain(ctx context.Context, in *UpsertRuleChainReq, opts ...grpc.CallOption) (*UpsertRuleChainReply, error) {
	out := new(UpsertRuleChainReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.RuleGo/UpsertRuleChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleGoClient) UpdateRuleChainBaseInfo(ctx context.Context, in *UpdateRuleChainBaseInfoReq, opts ...grpc.CallOption) (*UpdateRuleChainBaseInfoReply, error) {
	out := new(UpdateRuleChainBaseInfoReply)
	err := c.cc.Invoke(ctx, "/rulego.v1.RuleGo/UpdateRuleChainBaseInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleGoServer is the server API for RuleGo service.
// All implementations must embed UnimplementedRuleGoServer
// for forward compatibility
type RuleGoServer interface {
	// 获取所有组件
	GetComponents(context.Context, *GetComponentsReq) (*GetComponentsReply, error)
	// 获取所有规则链列表
	GetRegulationsList(context.Context, *GetRegulationsListReq) (*GetRegulationsListReply, error)
	// 获取单个规则链
	GetRuleChain(context.Context, *GetRuleChainReq) (*GetRuleChainReply, error)
	// 异步执行规则链
	ExecuteRuleChain(context.Context, *ExecuteRuleChainReq) (*ExecuteRuleChainReply, error)
	// 同步执行规则链
	ExecuteRuleChainSync(context.Context, *ExecuteRuleChainReq) (*ExecuteRuleChainSyncReply, error)
	// 部署或者下线规则链
	DeployRuleChain(context.Context, *DeployRuleChainReq) (*DeployRuleChainReply, error)
	// 新增或修改规则链
	UpsertRuleChain(context.Context, *UpsertRuleChainReq) (*UpsertRuleChainReply, error)
	// 保存规则链附加信息
	UpdateRuleChainBaseInfo(context.Context, *UpdateRuleChainBaseInfoReq) (*UpdateRuleChainBaseInfoReply, error)
	mustEmbedUnimplementedRuleGoServer()
}

// UnimplementedRuleGoServer must be embedded to have forward compatible implementations.
type UnimplementedRuleGoServer struct {
}

func (UnimplementedRuleGoServer) GetComponents(context.Context, *GetComponentsReq) (*GetComponentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComponents not implemented")
}
func (UnimplementedRuleGoServer) GetRegulationsList(context.Context, *GetRegulationsListReq) (*GetRegulationsListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegulationsList not implemented")
}
func (UnimplementedRuleGoServer) GetRuleChain(context.Context, *GetRuleChainReq) (*GetRuleChainReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRuleChain not implemented")
}
func (UnimplementedRuleGoServer) ExecuteRuleChain(context.Context, *ExecuteRuleChainReq) (*ExecuteRuleChainReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteRuleChain not implemented")
}
func (UnimplementedRuleGoServer) ExecuteRuleChainSync(context.Context, *ExecuteRuleChainReq) (*ExecuteRuleChainSyncReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteRuleChainSync not implemented")
}
func (UnimplementedRuleGoServer) DeployRuleChain(context.Context, *DeployRuleChainReq) (*DeployRuleChainReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployRuleChain not implemented")
}
func (UnimplementedRuleGoServer) UpsertRuleChain(context.Context, *UpsertRuleChainReq) (*UpsertRuleChainReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertRuleChain not implemented")
}
func (UnimplementedRuleGoServer) UpdateRuleChainBaseInfo(context.Context, *UpdateRuleChainBaseInfoReq) (*UpdateRuleChainBaseInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRuleChainBaseInfo not implemented")
}
func (UnimplementedRuleGoServer) mustEmbedUnimplementedRuleGoServer() {}

// UnsafeRuleGoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuleGoServer will
// result in compilation errors.
type UnsafeRuleGoServer interface {
	mustEmbedUnimplementedRuleGoServer()
}

func RegisterRuleGoServer(s grpc.ServiceRegistrar, srv RuleGoServer) {
	s.RegisterService(&RuleGo_ServiceDesc, srv)
}

func _RuleGo_GetComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComponentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleGoServer).GetComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.RuleGo/GetComponents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleGoServer).GetComponents(ctx, req.(*GetComponentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleGo_GetRegulationsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegulationsListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleGoServer).GetRegulationsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.RuleGo/GetRegulationsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleGoServer).GetRegulationsList(ctx, req.(*GetRegulationsListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleGo_GetRuleChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleChainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleGoServer).GetRuleChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.RuleGo/GetRuleChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleGoServer).GetRuleChain(ctx, req.(*GetRuleChainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleGo_ExecuteRuleChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRuleChainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleGoServer).ExecuteRuleChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.RuleGo/ExecuteRuleChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleGoServer).ExecuteRuleChain(ctx, req.(*ExecuteRuleChainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleGo_ExecuteRuleChainSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRuleChainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleGoServer).ExecuteRuleChainSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.RuleGo/ExecuteRuleChainSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleGoServer).ExecuteRuleChainSync(ctx, req.(*ExecuteRuleChainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleGo_DeployRuleChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRuleChainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleGoServer).DeployRuleChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.RuleGo/DeployRuleChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleGoServer).DeployRuleChain(ctx, req.(*DeployRuleChainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleGo_UpsertRuleChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRuleChainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleGoServer).UpsertRuleChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.RuleGo/UpsertRuleChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleGoServer).UpsertRuleChain(ctx, req.(*UpsertRuleChainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleGo_UpdateRuleChainBaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRuleChainBaseInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleGoServer).UpdateRuleChainBaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rulego.v1.RuleGo/UpdateRuleChainBaseInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleGoServer).UpdateRuleChainBaseInfo(ctx, req.(*UpdateRuleChainBaseInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RuleGo_ServiceDesc is the grpc.ServiceDesc for RuleGo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuleGo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rulego.v1.RuleGo",
	HandlerType: (*RuleGoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetComponents",
			Handler:    _RuleGo_GetComponents_Handler,
		},
		{
			MethodName: "GetRegulationsList",
			Handler:    _RuleGo_GetRegulationsList_Handler,
		},
		{
			MethodName: "GetRuleChain",
			Handler:    _RuleGo_GetRuleChain_Handler,
		},
		{
			MethodName: "ExecuteRuleChain",
			Handler:    _RuleGo_ExecuteRuleChain_Handler,
		},
		{
			MethodName: "ExecuteRuleChainSync",
			Handler:    _RuleGo_ExecuteRuleChainSync_Handler,
		},
		{
			MethodName: "DeployRuleChain",
			Handler:    _RuleGo_DeployRuleChain_Handler,
		},
		{
			MethodName: "UpsertRuleChain",
			Handler:    _RuleGo_UpsertRuleChain_Handler,
		},
		{
			MethodName: "UpdateRuleChainBaseInfo",
			Handler:    _RuleGo_UpdateRuleChainBaseInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rulego/v1/rules.proto",
}
