syntax = "proto3";

package rulego.v1;

import "google/api/annotations.proto";
import "google/protobuf/struct.proto";
import "validate/validate.proto";

option go_package = "ruleGoKratos/api/rulego/v1;v1";


// The greeting service definition.
service RunLog {
  rpc ListRunLogs (ListRunLogsRequest) returns (ListRunLogsReply) {
    option (google.api.http) = {
      get: "/api/v1/logs/runs"
    };
  }
  rpc GetRunLogByMsgId (GetRunLogByMsgIdReq) returns (RunLogItem) {
    option (google.api.http) = {
      get: "/api/v1/logs/runs/msgId"
    };
  }
}

message GetRunLogByMsgIdReq {
  string msgId = 1 [(validate.rules).string.min_len = 1];
}

message ListRunLogsRequest {
  int32 size = 1;
  int32 page = 2;
  string startTime = 3;
  string endTime = 4;
}

message ListRunLogsReply {
  repeated RunLogItem items = 1;
  int32 page = 2;
  int32 size = 3;
  int32 total = 4;
}

message RunLogItem {
  string id = 1;
  google.protobuf.Struct ruleChain = 2;
  google.protobuf.Struct metadata = 3;
  int64 startTs = 4;
  int64 endTs = 5;
  repeated google.protobuf.Struct logs = 6;
}
