// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/rulego/v1/run_log.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetRunLogByMsgIdReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRunLogByMsgIdReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRunLogByMsgIdReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRunLogByMsgIdReqMultiError, or nil if none found.
func (m *GetRunLogByMsgIdReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRunLogByMsgIdReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetMsgId()) < 1 {
		err := GetRunLogByMsgIdReqValidationError{
			field:  "MsgId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetRunLogByMsgIdReqMultiError(errors)
	}

	return nil
}

// GetRunLogByMsgIdReqMultiError is an error wrapping multiple validation
// errors returned by GetRunLogByMsgIdReq.ValidateAll() if the designated
// constraints aren't met.
type GetRunLogByMsgIdReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRunLogByMsgIdReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRunLogByMsgIdReqMultiError) AllErrors() []error { return m }

// GetRunLogByMsgIdReqValidationError is the validation error returned by
// GetRunLogByMsgIdReq.Validate if the designated constraints aren't met.
type GetRunLogByMsgIdReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRunLogByMsgIdReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRunLogByMsgIdReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRunLogByMsgIdReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRunLogByMsgIdReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRunLogByMsgIdReqValidationError) ErrorName() string {
	return "GetRunLogByMsgIdReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetRunLogByMsgIdReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRunLogByMsgIdReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRunLogByMsgIdReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRunLogByMsgIdReqValidationError{}

// Validate checks the field values on ListRunLogsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRunLogsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRunLogsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRunLogsRequestMultiError, or nil if none found.
func (m *ListRunLogsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRunLogsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Size

	// no validation rules for Page

	// no validation rules for StartTime

	// no validation rules for EndTime

	if len(errors) > 0 {
		return ListRunLogsRequestMultiError(errors)
	}

	return nil
}

// ListRunLogsRequestMultiError is an error wrapping multiple validation errors
// returned by ListRunLogsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListRunLogsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRunLogsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRunLogsRequestMultiError) AllErrors() []error { return m }

// ListRunLogsRequestValidationError is the validation error returned by
// ListRunLogsRequest.Validate if the designated constraints aren't met.
type ListRunLogsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRunLogsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRunLogsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRunLogsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRunLogsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRunLogsRequestValidationError) ErrorName() string {
	return "ListRunLogsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListRunLogsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRunLogsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRunLogsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRunLogsRequestValidationError{}

// Validate checks the field values on ListRunLogsReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListRunLogsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRunLogsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRunLogsReplyMultiError, or nil if none found.
func (m *ListRunLogsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRunLogsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRunLogsReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRunLogsReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRunLogsReplyValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Page

	// no validation rules for Size

	// no validation rules for Total

	if len(errors) > 0 {
		return ListRunLogsReplyMultiError(errors)
	}

	return nil
}

// ListRunLogsReplyMultiError is an error wrapping multiple validation errors
// returned by ListRunLogsReply.ValidateAll() if the designated constraints
// aren't met.
type ListRunLogsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRunLogsReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRunLogsReplyMultiError) AllErrors() []error { return m }

// ListRunLogsReplyValidationError is the validation error returned by
// ListRunLogsReply.Validate if the designated constraints aren't met.
type ListRunLogsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRunLogsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRunLogsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRunLogsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRunLogsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRunLogsReplyValidationError) ErrorName() string { return "ListRunLogsReplyValidationError" }

// Error satisfies the builtin error interface
func (e ListRunLogsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRunLogsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRunLogsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRunLogsReplyValidationError{}

// Validate checks the field values on RunLogItem with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RunLogItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RunLogItem with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RunLogItemMultiError, or
// nil if none found.
func (m *RunLogItem) ValidateAll() error {
	return m.validate(true)
}

func (m *RunLogItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetRuleChain()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RunLogItemValidationError{
					field:  "RuleChain",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RunLogItemValidationError{
					field:  "RuleChain",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRuleChain()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RunLogItemValidationError{
				field:  "RuleChain",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RunLogItemValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RunLogItemValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RunLogItemValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for StartTs

	// no validation rules for EndTs

	for idx, item := range m.GetLogs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RunLogItemValidationError{
						field:  fmt.Sprintf("Logs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RunLogItemValidationError{
						field:  fmt.Sprintf("Logs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RunLogItemValidationError{
					field:  fmt.Sprintf("Logs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return RunLogItemMultiError(errors)
	}

	return nil
}

// RunLogItemMultiError is an error wrapping multiple validation errors
// returned by RunLogItem.ValidateAll() if the designated constraints aren't met.
type RunLogItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RunLogItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RunLogItemMultiError) AllErrors() []error { return m }

// RunLogItemValidationError is the validation error returned by
// RunLogItem.Validate if the designated constraints aren't met.
type RunLogItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RunLogItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RunLogItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RunLogItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RunLogItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RunLogItemValidationError) ErrorName() string { return "RunLogItemValidationError" }

// Error satisfies the builtin error interface
func (e RunLogItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRunLogItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RunLogItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RunLogItemValidationError{}
