// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/rulego/v1/run_log.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunLog_ListRunLogs_FullMethodName      = "/rulego.v1.RunLog/ListRunLogs"
	RunLog_GetRunLogByMsgId_FullMethodName = "/rulego.v1.RunLog/GetRunLogByMsgId"
)

// RunLogClient is the client API for RunLog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type RunLogClient interface {
	ListRunLogs(ctx context.Context, in *ListRunLogsRequest, opts ...grpc.CallOption) (*ListRunLogsReply, error)
	GetRunLogByMsgId(ctx context.Context, in *GetRunLogByMsgIdReq, opts ...grpc.CallOption) (*RunLogItem, error)
}

type runLogClient struct {
	cc grpc.ClientConnInterface
}

func NewRunLogClient(cc grpc.ClientConnInterface) RunLogClient {
	return &runLogClient{cc}
}

func (c *runLogClient) ListRunLogs(ctx context.Context, in *ListRunLogsRequest, opts ...grpc.CallOption) (*ListRunLogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunLogsReply)
	err := c.cc.Invoke(ctx, RunLog_ListRunLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runLogClient) GetRunLogByMsgId(ctx context.Context, in *GetRunLogByMsgIdReq, opts ...grpc.CallOption) (*RunLogItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunLogItem)
	err := c.cc.Invoke(ctx, RunLog_GetRunLogByMsgId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunLogServer is the server API for RunLog service.
// All implementations must embed UnimplementedRunLogServer
// for forward compatibility.
//
// The greeting service definition.
type RunLogServer interface {
	ListRunLogs(context.Context, *ListRunLogsRequest) (*ListRunLogsReply, error)
	GetRunLogByMsgId(context.Context, *GetRunLogByMsgIdReq) (*RunLogItem, error)
	mustEmbedUnimplementedRunLogServer()
}

// UnimplementedRunLogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunLogServer struct{}

func (UnimplementedRunLogServer) ListRunLogs(context.Context, *ListRunLogsRequest) (*ListRunLogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRunLogs not implemented")
}
func (UnimplementedRunLogServer) GetRunLogByMsgId(context.Context, *GetRunLogByMsgIdReq) (*RunLogItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunLogByMsgId not implemented")
}
func (UnimplementedRunLogServer) mustEmbedUnimplementedRunLogServer() {}
func (UnimplementedRunLogServer) testEmbeddedByValue()                {}

// UnsafeRunLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunLogServer will
// result in compilation errors.
type UnsafeRunLogServer interface {
	mustEmbedUnimplementedRunLogServer()
}

func RegisterRunLogServer(s grpc.ServiceRegistrar, srv RunLogServer) {
	// If the following call pancis, it indicates UnimplementedRunLogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunLog_ServiceDesc, srv)
}

func _RunLog_ListRunLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunLogServer).ListRunLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunLog_ListRunLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunLogServer).ListRunLogs(ctx, req.(*ListRunLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunLog_GetRunLogByMsgId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunLogByMsgIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunLogServer).GetRunLogByMsgId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunLog_GetRunLogByMsgId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunLogServer).GetRunLogByMsgId(ctx, req.(*GetRunLogByMsgIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RunLog_ServiceDesc is the grpc.ServiceDesc for RunLog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunLog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rulego.v1.RunLog",
	HandlerType: (*RunLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRunLogs",
			Handler:    _RunLog_ListRunLogs_Handler,
		},
		{
			MethodName: "GetRunLogByMsgId",
			Handler:    _RunLog_GetRunLogByMsgId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rulego/v1/run_log.proto",
}
