// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.21.12
// source: api/rulego/v1/run_log.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRunLogGetRunLogByMsgId = "/rulego.v1.RunLog/GetRunLogByMsgId"
const OperationRunLogListRunLogs = "/rulego.v1.RunLog/ListRunLogs"

type RunLogHTTPServer interface {
	GetRunLogByMsgId(context.Context, *GetRunLogByMsgIdReq) (*RunLogItem, error)
	ListRunLogs(context.Context, *ListRunLogsRequest) (*ListRunLogsReply, error)
}

func RegisterRunLogHTTPServer(s *http.Server, srv RunLogHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/logs/runs", _RunLog_ListRunLogs0_HTTP_Handler(srv))
	r.GET("/api/v1/logs/runs/msgId", _RunLog_GetRunLogByMsgId0_HTTP_Handler(srv))
}

func _RunLog_ListRunLogs0_HTTP_Handler(srv RunLogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRunLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRunLogListRunLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRunLogs(ctx, req.(*ListRunLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRunLogsReply)
		return ctx.Result(200, reply)
	}
}

func _RunLog_GetRunLogByMsgId0_HTTP_Handler(srv RunLogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRunLogByMsgIdReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRunLogGetRunLogByMsgId)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRunLogByMsgId(ctx, req.(*GetRunLogByMsgIdReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RunLogItem)
		return ctx.Result(200, reply)
	}
}

type RunLogHTTPClient interface {
	GetRunLogByMsgId(ctx context.Context, req *GetRunLogByMsgIdReq, opts ...http.CallOption) (rsp *RunLogItem, err error)
	ListRunLogs(ctx context.Context, req *ListRunLogsRequest, opts ...http.CallOption) (rsp *ListRunLogsReply, err error)
}

type RunLogHTTPClientImpl struct {
	cc *http.Client
}

func NewRunLogHTTPClient(client *http.Client) RunLogHTTPClient {
	return &RunLogHTTPClientImpl{client}
}

func (c *RunLogHTTPClientImpl) GetRunLogByMsgId(ctx context.Context, in *GetRunLogByMsgIdReq, opts ...http.CallOption) (*RunLogItem, error) {
	var out RunLogItem
	pattern := "/api/v1/logs/runs/msgId"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRunLogGetRunLogByMsgId))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RunLogHTTPClientImpl) ListRunLogs(ctx context.Context, in *ListRunLogsRequest, opts ...http.CallOption) (*ListRunLogsReply, error) {
	var out ListRunLogsReply
	pattern := "/api/v1/logs/runs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRunLogListRunLogs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
