// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: api/rulego/v1/scheduled_task_service.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationScheduledTaskServiceCreateScheduledTask = "/rulego.v1.ScheduledTaskService/CreateScheduledTask"
const OperationScheduledTaskServiceDeleteScheduledTask = "/rulego.v1.ScheduledTaskService/DeleteScheduledTask"
const OperationScheduledTaskServiceDisableScheduledTask = "/rulego.v1.ScheduledTaskService/DisableScheduledTask"
const OperationScheduledTaskServiceEnableScheduledTask = "/rulego.v1.ScheduledTaskService/EnableScheduledTask"
const OperationScheduledTaskServiceGetScheduledTask = "/rulego.v1.ScheduledTaskService/GetScheduledTask"
const OperationScheduledTaskServiceListScheduledTaskRuns = "/rulego.v1.ScheduledTaskService/ListScheduledTaskRuns"
const OperationScheduledTaskServiceListScheduledTasks = "/rulego.v1.ScheduledTaskService/ListScheduledTasks"
const OperationScheduledTaskServiceUpdateScheduledTask = "/rulego.v1.ScheduledTaskService/UpdateScheduledTask"

type ScheduledTaskServiceHTTPServer interface {
	CreateScheduledTask(context.Context, *CreateScheduledTaskReq) (*CreateScheduledTaskReply, error)
	DeleteScheduledTask(context.Context, *DeleteScheduledTaskReq) (*DeleteScheduledTaskReply, error)
	DisableScheduledTask(context.Context, *DisableScheduledTaskReq) (*DisableScheduledTaskReply, error)
	EnableScheduledTask(context.Context, *EnableScheduledTaskReq) (*EnableScheduledTaskReply, error)
	GetScheduledTask(context.Context, *GetScheduledTaskReq) (*GetScheduledTaskReply, error)
	ListScheduledTaskRuns(context.Context, *ListScheduledTaskRunsReq) (*ListScheduledTaskRunsReply, error)
	ListScheduledTasks(context.Context, *ListScheduledTasksReq) (*ListScheduledTasksReply, error)
	UpdateScheduledTask(context.Context, *UpdateScheduledTaskReq) (*UpdateScheduledTaskReply, error)
}

func RegisterScheduledTaskServiceHTTPServer(s *http.Server, srv ScheduledTaskServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/scheduled-tasks", _ScheduledTaskService_CreateScheduledTask0_HTTP_Handler(srv))
	r.GET("/api/v1/scheduled-tasks/{id}", _ScheduledTaskService_GetScheduledTask0_HTTP_Handler(srv))
	r.GET("/api/v1/scheduled-tasks", _ScheduledTaskService_ListScheduledTasks0_HTTP_Handler(srv))
	r.PUT("/api/v1/scheduled-tasks/{id}", _ScheduledTaskService_UpdateScheduledTask0_HTTP_Handler(srv))
	r.DELETE("/api/v1/scheduled-tasks/{id}", _ScheduledTaskService_DeleteScheduledTask0_HTTP_Handler(srv))
	r.POST("/api/v1/scheduled-tasks/{id}/enable", _ScheduledTaskService_EnableScheduledTask0_HTTP_Handler(srv))
	r.POST("/api/v1/scheduled-tasks/{id}/disable", _ScheduledTaskService_DisableScheduledTask0_HTTP_Handler(srv))
	r.GET("/api/v1/scheduled-tasks/{task_id}/runs", _ScheduledTaskService_ListScheduledTaskRuns0_HTTP_Handler(srv))
}

func _ScheduledTaskService_CreateScheduledTask0_HTTP_Handler(srv ScheduledTaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateScheduledTaskReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationScheduledTaskServiceCreateScheduledTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateScheduledTask(ctx, req.(*CreateScheduledTaskReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateScheduledTaskReply)
		return ctx.Result(200, reply)
	}
}

func _ScheduledTaskService_GetScheduledTask0_HTTP_Handler(srv ScheduledTaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetScheduledTaskReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationScheduledTaskServiceGetScheduledTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetScheduledTask(ctx, req.(*GetScheduledTaskReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetScheduledTaskReply)
		return ctx.Result(200, reply)
	}
}

func _ScheduledTaskService_ListScheduledTasks0_HTTP_Handler(srv ScheduledTaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListScheduledTasksReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationScheduledTaskServiceListScheduledTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListScheduledTasks(ctx, req.(*ListScheduledTasksReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListScheduledTasksReply)
		return ctx.Result(200, reply)
	}
}

func _ScheduledTaskService_UpdateScheduledTask0_HTTP_Handler(srv ScheduledTaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateScheduledTaskReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationScheduledTaskServiceUpdateScheduledTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateScheduledTask(ctx, req.(*UpdateScheduledTaskReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateScheduledTaskReply)
		return ctx.Result(200, reply)
	}
}

func _ScheduledTaskService_DeleteScheduledTask0_HTTP_Handler(srv ScheduledTaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteScheduledTaskReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationScheduledTaskServiceDeleteScheduledTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteScheduledTask(ctx, req.(*DeleteScheduledTaskReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteScheduledTaskReply)
		return ctx.Result(200, reply)
	}
}

func _ScheduledTaskService_EnableScheduledTask0_HTTP_Handler(srv ScheduledTaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EnableScheduledTaskReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationScheduledTaskServiceEnableScheduledTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EnableScheduledTask(ctx, req.(*EnableScheduledTaskReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EnableScheduledTaskReply)
		return ctx.Result(200, reply)
	}
}

func _ScheduledTaskService_DisableScheduledTask0_HTTP_Handler(srv ScheduledTaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DisableScheduledTaskReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationScheduledTaskServiceDisableScheduledTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DisableScheduledTask(ctx, req.(*DisableScheduledTaskReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DisableScheduledTaskReply)
		return ctx.Result(200, reply)
	}
}

func _ScheduledTaskService_ListScheduledTaskRuns0_HTTP_Handler(srv ScheduledTaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListScheduledTaskRunsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationScheduledTaskServiceListScheduledTaskRuns)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListScheduledTaskRuns(ctx, req.(*ListScheduledTaskRunsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListScheduledTaskRunsReply)
		return ctx.Result(200, reply)
	}
}

type ScheduledTaskServiceHTTPClient interface {
	CreateScheduledTask(ctx context.Context, req *CreateScheduledTaskReq, opts ...http.CallOption) (rsp *CreateScheduledTaskReply, err error)
	DeleteScheduledTask(ctx context.Context, req *DeleteScheduledTaskReq, opts ...http.CallOption) (rsp *DeleteScheduledTaskReply, err error)
	DisableScheduledTask(ctx context.Context, req *DisableScheduledTaskReq, opts ...http.CallOption) (rsp *DisableScheduledTaskReply, err error)
	EnableScheduledTask(ctx context.Context, req *EnableScheduledTaskReq, opts ...http.CallOption) (rsp *EnableScheduledTaskReply, err error)
	GetScheduledTask(ctx context.Context, req *GetScheduledTaskReq, opts ...http.CallOption) (rsp *GetScheduledTaskReply, err error)
	ListScheduledTaskRuns(ctx context.Context, req *ListScheduledTaskRunsReq, opts ...http.CallOption) (rsp *ListScheduledTaskRunsReply, err error)
	ListScheduledTasks(ctx context.Context, req *ListScheduledTasksReq, opts ...http.CallOption) (rsp *ListScheduledTasksReply, err error)
	UpdateScheduledTask(ctx context.Context, req *UpdateScheduledTaskReq, opts ...http.CallOption) (rsp *UpdateScheduledTaskReply, err error)
}

type ScheduledTaskServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewScheduledTaskServiceHTTPClient(client *http.Client) ScheduledTaskServiceHTTPClient {
	return &ScheduledTaskServiceHTTPClientImpl{client}
}

func (c *ScheduledTaskServiceHTTPClientImpl) CreateScheduledTask(ctx context.Context, in *CreateScheduledTaskReq, opts ...http.CallOption) (*CreateScheduledTaskReply, error) {
	var out CreateScheduledTaskReply
	pattern := "/api/v1/scheduled-tasks"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationScheduledTaskServiceCreateScheduledTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ScheduledTaskServiceHTTPClientImpl) DeleteScheduledTask(ctx context.Context, in *DeleteScheduledTaskReq, opts ...http.CallOption) (*DeleteScheduledTaskReply, error) {
	var out DeleteScheduledTaskReply
	pattern := "/api/v1/scheduled-tasks/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationScheduledTaskServiceDeleteScheduledTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ScheduledTaskServiceHTTPClientImpl) DisableScheduledTask(ctx context.Context, in *DisableScheduledTaskReq, opts ...http.CallOption) (*DisableScheduledTaskReply, error) {
	var out DisableScheduledTaskReply
	pattern := "/api/v1/scheduled-tasks/{id}/disable"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationScheduledTaskServiceDisableScheduledTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ScheduledTaskServiceHTTPClientImpl) EnableScheduledTask(ctx context.Context, in *EnableScheduledTaskReq, opts ...http.CallOption) (*EnableScheduledTaskReply, error) {
	var out EnableScheduledTaskReply
	pattern := "/api/v1/scheduled-tasks/{id}/enable"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationScheduledTaskServiceEnableScheduledTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ScheduledTaskServiceHTTPClientImpl) GetScheduledTask(ctx context.Context, in *GetScheduledTaskReq, opts ...http.CallOption) (*GetScheduledTaskReply, error) {
	var out GetScheduledTaskReply
	pattern := "/api/v1/scheduled-tasks/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationScheduledTaskServiceGetScheduledTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ScheduledTaskServiceHTTPClientImpl) ListScheduledTaskRuns(ctx context.Context, in *ListScheduledTaskRunsReq, opts ...http.CallOption) (*ListScheduledTaskRunsReply, error) {
	var out ListScheduledTaskRunsReply
	pattern := "/api/v1/scheduled-tasks/{task_id}/runs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationScheduledTaskServiceListScheduledTaskRuns))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ScheduledTaskServiceHTTPClientImpl) ListScheduledTasks(ctx context.Context, in *ListScheduledTasksReq, opts ...http.CallOption) (*ListScheduledTasksReply, error) {
	var out ListScheduledTasksReply
	pattern := "/api/v1/scheduled-tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationScheduledTaskServiceListScheduledTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ScheduledTaskServiceHTTPClientImpl) UpdateScheduledTask(ctx context.Context, in *UpdateScheduledTaskReq, opts ...http.CallOption) (*UpdateScheduledTaskReply, error) {
	var out UpdateScheduledTaskReply
	pattern := "/api/v1/scheduled-tasks/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationScheduledTaskServiceUpdateScheduledTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
