// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/rulego/v1/task_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskBoardService_CreateTask_FullMethodName           = "/rulego.v1.TaskBoardService/CreateTask"
	TaskBoardService_GetTask_FullMethodName              = "/rulego.v1.TaskBoardService/GetTask"
	TaskBoardService_ListTasks_FullMethodName            = "/rulego.v1.TaskBoardService/ListTasks"
	TaskBoardService_UpdateTask_FullMethodName           = "/rulego.v1.TaskBoardService/UpdateTask"
	TaskBoardService_DeleteTask_FullMethodName           = "/rulego.v1.TaskBoardService/DeleteTask"
	TaskBoardService_ExecuteTaskRuleChain_FullMethodName = "/rulego.v1.TaskBoardService/ExecuteTaskRuleChain"
	TaskBoardService_CreateChildTask_FullMethodName      = "/rulego.v1.TaskBoardService/CreateChildTask"
	TaskBoardService_ListChildTasks_FullMethodName       = "/rulego.v1.TaskBoardService/ListChildTasks"
)

// TaskBoardServiceClient is the client API for TaskBoardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 任务看板服务
type TaskBoardServiceClient interface {
	// 创建任务
	CreateTask(ctx context.Context, in *CreateTaskReq, opts ...grpc.CallOption) (*CreateTaskReply, error)
	// 获取任务详情
	GetTask(ctx context.Context, in *GetTaskReq, opts ...grpc.CallOption) (*GetTaskReply, error)
	// 查询任务列表
	ListTasks(ctx context.Context, in *ListTasksReq, opts ...grpc.CallOption) (*ListTasksReply, error)
	// 更新任务
	UpdateTask(ctx context.Context, in *UpdateTaskReq, opts ...grpc.CallOption) (*UpdateTaskReply, error)
	// 删除任务
	DeleteTask(ctx context.Context, in *DeleteTaskReq, opts ...grpc.CallOption) (*DeleteTaskReply, error)
	// 执行任务关联的规则链
	ExecuteTaskRuleChain(ctx context.Context, in *ExecuteTaskRuleChainReq, opts ...grpc.CallOption) (*ExecuteTaskRuleChainReply, error)
	// 创建子任务
	CreateChildTask(ctx context.Context, in *CreateChildTaskReq, opts ...grpc.CallOption) (*CreateChildTaskReply, error)
	// 查询子任务列表
	ListChildTasks(ctx context.Context, in *ListChildTasksReq, opts ...grpc.CallOption) (*ListChildTasksReply, error)
}

type taskBoardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskBoardServiceClient(cc grpc.ClientConnInterface) TaskBoardServiceClient {
	return &taskBoardServiceClient{cc}
}

func (c *taskBoardServiceClient) CreateTask(ctx context.Context, in *CreateTaskReq, opts ...grpc.CallOption) (*CreateTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskReply)
	err := c.cc.Invoke(ctx, TaskBoardService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardServiceClient) GetTask(ctx context.Context, in *GetTaskReq, opts ...grpc.CallOption) (*GetTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskReply)
	err := c.cc.Invoke(ctx, TaskBoardService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardServiceClient) ListTasks(ctx context.Context, in *ListTasksReq, opts ...grpc.CallOption) (*ListTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksReply)
	err := c.cc.Invoke(ctx, TaskBoardService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskReq, opts ...grpc.CallOption) (*UpdateTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTaskReply)
	err := c.cc.Invoke(ctx, TaskBoardService_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardServiceClient) DeleteTask(ctx context.Context, in *DeleteTaskReq, opts ...grpc.CallOption) (*DeleteTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskReply)
	err := c.cc.Invoke(ctx, TaskBoardService_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardServiceClient) ExecuteTaskRuleChain(ctx context.Context, in *ExecuteTaskRuleChainReq, opts ...grpc.CallOption) (*ExecuteTaskRuleChainReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteTaskRuleChainReply)
	err := c.cc.Invoke(ctx, TaskBoardService_ExecuteTaskRuleChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardServiceClient) CreateChildTask(ctx context.Context, in *CreateChildTaskReq, opts ...grpc.CallOption) (*CreateChildTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChildTaskReply)
	err := c.cc.Invoke(ctx, TaskBoardService_CreateChildTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskBoardServiceClient) ListChildTasks(ctx context.Context, in *ListChildTasksReq, opts ...grpc.CallOption) (*ListChildTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChildTasksReply)
	err := c.cc.Invoke(ctx, TaskBoardService_ListChildTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskBoardServiceServer is the server API for TaskBoardService service.
// All implementations must embed UnimplementedTaskBoardServiceServer
// for forward compatibility.
//
// 任务看板服务
type TaskBoardServiceServer interface {
	// 创建任务
	CreateTask(context.Context, *CreateTaskReq) (*CreateTaskReply, error)
	// 获取任务详情
	GetTask(context.Context, *GetTaskReq) (*GetTaskReply, error)
	// 查询任务列表
	ListTasks(context.Context, *ListTasksReq) (*ListTasksReply, error)
	// 更新任务
	UpdateTask(context.Context, *UpdateTaskReq) (*UpdateTaskReply, error)
	// 删除任务
	DeleteTask(context.Context, *DeleteTaskReq) (*DeleteTaskReply, error)
	// 执行任务关联的规则链
	ExecuteTaskRuleChain(context.Context, *ExecuteTaskRuleChainReq) (*ExecuteTaskRuleChainReply, error)
	// 创建子任务
	CreateChildTask(context.Context, *CreateChildTaskReq) (*CreateChildTaskReply, error)
	// 查询子任务列表
	ListChildTasks(context.Context, *ListChildTasksReq) (*ListChildTasksReply, error)
	mustEmbedUnimplementedTaskBoardServiceServer()
}

// UnimplementedTaskBoardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskBoardServiceServer struct{}

func (UnimplementedTaskBoardServiceServer) CreateTask(context.Context, *CreateTaskReq) (*CreateTaskReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedTaskBoardServiceServer) GetTask(context.Context, *GetTaskReq) (*GetTaskReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskBoardServiceServer) ListTasks(context.Context, *ListTasksReq) (*ListTasksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedTaskBoardServiceServer) UpdateTask(context.Context, *UpdateTaskReq) (*UpdateTaskReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedTaskBoardServiceServer) DeleteTask(context.Context, *DeleteTaskReq) (*DeleteTaskReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedTaskBoardServiceServer) ExecuteTaskRuleChain(context.Context, *ExecuteTaskRuleChainReq) (*ExecuteTaskRuleChainReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTaskRuleChain not implemented")
}
func (UnimplementedTaskBoardServiceServer) CreateChildTask(context.Context, *CreateChildTaskReq) (*CreateChildTaskReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChildTask not implemented")
}
func (UnimplementedTaskBoardServiceServer) ListChildTasks(context.Context, *ListChildTasksReq) (*ListChildTasksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChildTasks not implemented")
}
func (UnimplementedTaskBoardServiceServer) mustEmbedUnimplementedTaskBoardServiceServer() {}
func (UnimplementedTaskBoardServiceServer) testEmbeddedByValue()                          {}

// UnsafeTaskBoardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskBoardServiceServer will
// result in compilation errors.
type UnsafeTaskBoardServiceServer interface {
	mustEmbedUnimplementedTaskBoardServiceServer()
}

func RegisterTaskBoardServiceServer(s grpc.ServiceRegistrar, srv TaskBoardServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskBoardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskBoardService_ServiceDesc, srv)
}

func _TaskBoardService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoardService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServiceServer).CreateTask(ctx, req.(*CreateTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoardService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoardService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServiceServer).GetTask(ctx, req.(*GetTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoardService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoardService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServiceServer).ListTasks(ctx, req.(*ListTasksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoardService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoardService_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServiceServer).UpdateTask(ctx, req.(*UpdateTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoardService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoardService_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServiceServer).DeleteTask(ctx, req.(*DeleteTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoardService_ExecuteTaskRuleChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTaskRuleChainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServiceServer).ExecuteTaskRuleChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoardService_ExecuteTaskRuleChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServiceServer).ExecuteTaskRuleChain(ctx, req.(*ExecuteTaskRuleChainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoardService_CreateChildTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChildTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServiceServer).CreateChildTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoardService_CreateChildTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServiceServer).CreateChildTask(ctx, req.(*CreateChildTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskBoardService_ListChildTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChildTasksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskBoardServiceServer).ListChildTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskBoardService_ListChildTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskBoardServiceServer).ListChildTasks(ctx, req.(*ListChildTasksReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskBoardService_ServiceDesc is the grpc.ServiceDesc for TaskBoardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskBoardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rulego.v1.TaskBoardService",
	HandlerType: (*TaskBoardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _TaskBoardService_CreateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskBoardService_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _TaskBoardService_ListTasks_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _TaskBoardService_UpdateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _TaskBoardService_DeleteTask_Handler,
		},
		{
			MethodName: "ExecuteTaskRuleChain",
			Handler:    _TaskBoardService_ExecuteTaskRuleChain_Handler,
		},
		{
			MethodName: "CreateChildTask",
			Handler:    _TaskBoardService_CreateChildTask_Handler,
		},
		{
			MethodName: "ListChildTasks",
			Handler:    _TaskBoardService_ListChildTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rulego/v1/task_service.proto",
}

const (
	ServiceManagementService_CreateService_FullMethodName = "/rulego.v1.ServiceManagementService/CreateService"
	ServiceManagementService_GetService_FullMethodName    = "/rulego.v1.ServiceManagementService/GetService"
	ServiceManagementService_ListServices_FullMethodName  = "/rulego.v1.ServiceManagementService/ListServices"
	ServiceManagementService_UpdateService_FullMethodName = "/rulego.v1.ServiceManagementService/UpdateService"
	ServiceManagementService_DeleteService_FullMethodName = "/rulego.v1.ServiceManagementService/DeleteService"
)

// ServiceManagementServiceClient is the client API for ServiceManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 服务管理服务
type ServiceManagementServiceClient interface {
	// 创建服务
	CreateService(ctx context.Context, in *CreateServiceReq, opts ...grpc.CallOption) (*CreateServiceReply, error)
	// 获取服务详情
	GetService(ctx context.Context, in *GetServiceReq, opts ...grpc.CallOption) (*GetServiceReply, error)
	// 查询服务列表
	ListServices(ctx context.Context, in *ListServicesReq, opts ...grpc.CallOption) (*ListServicesReply, error)
	// 更新服务
	UpdateService(ctx context.Context, in *UpdateServiceReq, opts ...grpc.CallOption) (*UpdateServiceReply, error)
	// 删除服务
	DeleteService(ctx context.Context, in *DeleteServiceReq, opts ...grpc.CallOption) (*DeleteServiceReply, error)
}

type serviceManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceManagementServiceClient(cc grpc.ClientConnInterface) ServiceManagementServiceClient {
	return &serviceManagementServiceClient{cc}
}

func (c *serviceManagementServiceClient) CreateService(ctx context.Context, in *CreateServiceReq, opts ...grpc.CallOption) (*CreateServiceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateServiceReply)
	err := c.cc.Invoke(ctx, ServiceManagementService_CreateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagementServiceClient) GetService(ctx context.Context, in *GetServiceReq, opts ...grpc.CallOption) (*GetServiceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceReply)
	err := c.cc.Invoke(ctx, ServiceManagementService_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagementServiceClient) ListServices(ctx context.Context, in *ListServicesReq, opts ...grpc.CallOption) (*ListServicesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesReply)
	err := c.cc.Invoke(ctx, ServiceManagementService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagementServiceClient) UpdateService(ctx context.Context, in *UpdateServiceReq, opts ...grpc.CallOption) (*UpdateServiceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateServiceReply)
	err := c.cc.Invoke(ctx, ServiceManagementService_UpdateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagementServiceClient) DeleteService(ctx context.Context, in *DeleteServiceReq, opts ...grpc.CallOption) (*DeleteServiceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteServiceReply)
	err := c.cc.Invoke(ctx, ServiceManagementService_DeleteService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceManagementServiceServer is the server API for ServiceManagementService service.
// All implementations must embed UnimplementedServiceManagementServiceServer
// for forward compatibility.
//
// 服务管理服务
type ServiceManagementServiceServer interface {
	// 创建服务
	CreateService(context.Context, *CreateServiceReq) (*CreateServiceReply, error)
	// 获取服务详情
	GetService(context.Context, *GetServiceReq) (*GetServiceReply, error)
	// 查询服务列表
	ListServices(context.Context, *ListServicesReq) (*ListServicesReply, error)
	// 更新服务
	UpdateService(context.Context, *UpdateServiceReq) (*UpdateServiceReply, error)
	// 删除服务
	DeleteService(context.Context, *DeleteServiceReq) (*DeleteServiceReply, error)
	mustEmbedUnimplementedServiceManagementServiceServer()
}

// UnimplementedServiceManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceManagementServiceServer struct{}

func (UnimplementedServiceManagementServiceServer) CreateService(context.Context, *CreateServiceReq) (*CreateServiceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateService not implemented")
}
func (UnimplementedServiceManagementServiceServer) GetService(context.Context, *GetServiceReq) (*GetServiceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedServiceManagementServiceServer) ListServices(context.Context, *ListServicesReq) (*ListServicesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedServiceManagementServiceServer) UpdateService(context.Context, *UpdateServiceReq) (*UpdateServiceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateService not implemented")
}
func (UnimplementedServiceManagementServiceServer) DeleteService(context.Context, *DeleteServiceReq) (*DeleteServiceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteService not implemented")
}
func (UnimplementedServiceManagementServiceServer) mustEmbedUnimplementedServiceManagementServiceServer() {
}
func (UnimplementedServiceManagementServiceServer) testEmbeddedByValue() {}

// UnsafeServiceManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceManagementServiceServer will
// result in compilation errors.
type UnsafeServiceManagementServiceServer interface {
	mustEmbedUnimplementedServiceManagementServiceServer()
}

func RegisterServiceManagementServiceServer(s grpc.ServiceRegistrar, srv ServiceManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceManagementService_ServiceDesc, srv)
}

func _ServiceManagementService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagementServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceManagementService_CreateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagementServiceServer).CreateService(ctx, req.(*CreateServiceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManagementService_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagementServiceServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceManagementService_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagementServiceServer).GetService(ctx, req.(*GetServiceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManagementService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagementServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceManagementService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagementServiceServer).ListServices(ctx, req.(*ListServicesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManagementService_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagementServiceServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceManagementService_UpdateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagementServiceServer).UpdateService(ctx, req.(*UpdateServiceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManagementService_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServiceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagementServiceServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceManagementService_DeleteService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagementServiceServer).DeleteService(ctx, req.(*DeleteServiceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceManagementService_ServiceDesc is the grpc.ServiceDesc for ServiceManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rulego.v1.ServiceManagementService",
	HandlerType: (*ServiceManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateService",
			Handler:    _ServiceManagementService_CreateService_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _ServiceManagementService_GetService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _ServiceManagementService_ListServices_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _ServiceManagementService_UpdateService_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _ServiceManagementService_DeleteService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rulego/v1/task_service.proto",
}
