// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: api/rulego/v1/task_service.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTaskBoardServiceCreateChildTask = "/rulego.v1.TaskBoardService/CreateChildTask"
const OperationTaskBoardServiceCreateTask = "/rulego.v1.TaskBoardService/CreateTask"
const OperationTaskBoardServiceDeleteTask = "/rulego.v1.TaskBoardService/DeleteTask"
const OperationTaskBoardServiceExecuteTaskRuleChain = "/rulego.v1.TaskBoardService/ExecuteTaskRuleChain"
const OperationTaskBoardServiceGetTask = "/rulego.v1.TaskBoardService/GetTask"
const OperationTaskBoardServiceListChildTasks = "/rulego.v1.TaskBoardService/ListChildTasks"
const OperationTaskBoardServiceListTasks = "/rulego.v1.TaskBoardService/ListTasks"
const OperationTaskBoardServiceUpdateTask = "/rulego.v1.TaskBoardService/UpdateTask"

type TaskBoardServiceHTTPServer interface {
	// CreateChildTask 创建子任务
	CreateChildTask(context.Context, *CreateChildTaskReq) (*CreateChildTaskReply, error)
	// CreateTask 创建任务
	CreateTask(context.Context, *CreateTaskReq) (*CreateTaskReply, error)
	// DeleteTask 删除任务
	DeleteTask(context.Context, *DeleteTaskReq) (*DeleteTaskReply, error)
	// ExecuteTaskRuleChain 执行任务关联的规则链
	ExecuteTaskRuleChain(context.Context, *ExecuteTaskRuleChainReq) (*ExecuteTaskRuleChainReply, error)
	// GetTask 获取任务详情
	GetTask(context.Context, *GetTaskReq) (*GetTaskReply, error)
	// ListChildTasks 查询子任务列表
	ListChildTasks(context.Context, *ListChildTasksReq) (*ListChildTasksReply, error)
	// ListTasks 查询任务列表
	ListTasks(context.Context, *ListTasksReq) (*ListTasksReply, error)
	// UpdateTask 更新任务
	UpdateTask(context.Context, *UpdateTaskReq) (*UpdateTaskReply, error)
}

func RegisterTaskBoardServiceHTTPServer(s *http.Server, srv TaskBoardServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/tasks", _TaskBoardService_CreateTask0_HTTP_Handler(srv))
	r.GET("/api/v1/tasks/{id}", _TaskBoardService_GetTask0_HTTP_Handler(srv))
	r.GET("/api/v1/tasks", _TaskBoardService_ListTasks0_HTTP_Handler(srv))
	r.PUT("/api/v1/tasks/{id}", _TaskBoardService_UpdateTask0_HTTP_Handler(srv))
	r.DELETE("/api/v1/tasks/{id}", _TaskBoardService_DeleteTask0_HTTP_Handler(srv))
	r.POST("/api/v1/tasks/{id}/execute", _TaskBoardService_ExecuteTaskRuleChain0_HTTP_Handler(srv))
	r.POST("/api/v1/tasks/{parent_id}/children", _TaskBoardService_CreateChildTask0_HTTP_Handler(srv))
	r.GET("/api/v1/tasks/{parent_id}/children", _TaskBoardService_ListChildTasks0_HTTP_Handler(srv))
}

func _TaskBoardService_CreateTask0_HTTP_Handler(srv TaskBoardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTaskReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskBoardServiceCreateTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTask(ctx, req.(*CreateTaskReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTaskReply)
		return ctx.Result(200, reply)
	}
}

func _TaskBoardService_GetTask0_HTTP_Handler(srv TaskBoardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTaskReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskBoardServiceGetTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTask(ctx, req.(*GetTaskReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTaskReply)
		return ctx.Result(200, reply)
	}
}

func _TaskBoardService_ListTasks0_HTTP_Handler(srv TaskBoardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTasksReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskBoardServiceListTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTasks(ctx, req.(*ListTasksReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTasksReply)
		return ctx.Result(200, reply)
	}
}

func _TaskBoardService_UpdateTask0_HTTP_Handler(srv TaskBoardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTaskReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskBoardServiceUpdateTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTask(ctx, req.(*UpdateTaskReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateTaskReply)
		return ctx.Result(200, reply)
	}
}

func _TaskBoardService_DeleteTask0_HTTP_Handler(srv TaskBoardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTaskReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskBoardServiceDeleteTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTask(ctx, req.(*DeleteTaskReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteTaskReply)
		return ctx.Result(200, reply)
	}
}

func _TaskBoardService_ExecuteTaskRuleChain0_HTTP_Handler(srv TaskBoardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExecuteTaskRuleChainReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskBoardServiceExecuteTaskRuleChain)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExecuteTaskRuleChain(ctx, req.(*ExecuteTaskRuleChainReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExecuteTaskRuleChainReply)
		return ctx.Result(200, reply)
	}
}

func _TaskBoardService_CreateChildTask0_HTTP_Handler(srv TaskBoardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateChildTaskReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskBoardServiceCreateChildTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateChildTask(ctx, req.(*CreateChildTaskReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateChildTaskReply)
		return ctx.Result(200, reply)
	}
}

func _TaskBoardService_ListChildTasks0_HTTP_Handler(srv TaskBoardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListChildTasksReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskBoardServiceListChildTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListChildTasks(ctx, req.(*ListChildTasksReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListChildTasksReply)
		return ctx.Result(200, reply)
	}
}

type TaskBoardServiceHTTPClient interface {
	// CreateChildTask 创建子任务
	CreateChildTask(ctx context.Context, req *CreateChildTaskReq, opts ...http.CallOption) (rsp *CreateChildTaskReply, err error)
	// CreateTask 创建任务
	CreateTask(ctx context.Context, req *CreateTaskReq, opts ...http.CallOption) (rsp *CreateTaskReply, err error)
	// DeleteTask 删除任务
	DeleteTask(ctx context.Context, req *DeleteTaskReq, opts ...http.CallOption) (rsp *DeleteTaskReply, err error)
	// ExecuteTaskRuleChain 执行任务关联的规则链
	ExecuteTaskRuleChain(ctx context.Context, req *ExecuteTaskRuleChainReq, opts ...http.CallOption) (rsp *ExecuteTaskRuleChainReply, err error)
	// GetTask 获取任务详情
	GetTask(ctx context.Context, req *GetTaskReq, opts ...http.CallOption) (rsp *GetTaskReply, err error)
	// ListChildTasks 查询子任务列表
	ListChildTasks(ctx context.Context, req *ListChildTasksReq, opts ...http.CallOption) (rsp *ListChildTasksReply, err error)
	// ListTasks 查询任务列表
	ListTasks(ctx context.Context, req *ListTasksReq, opts ...http.CallOption) (rsp *ListTasksReply, err error)
	// UpdateTask 更新任务
	UpdateTask(ctx context.Context, req *UpdateTaskReq, opts ...http.CallOption) (rsp *UpdateTaskReply, err error)
}

type TaskBoardServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTaskBoardServiceHTTPClient(client *http.Client) TaskBoardServiceHTTPClient {
	return &TaskBoardServiceHTTPClientImpl{client}
}

// CreateChildTask 创建子任务
func (c *TaskBoardServiceHTTPClientImpl) CreateChildTask(ctx context.Context, in *CreateChildTaskReq, opts ...http.CallOption) (*CreateChildTaskReply, error) {
	var out CreateChildTaskReply
	pattern := "/api/v1/tasks/{parent_id}/children"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTaskBoardServiceCreateChildTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateTask 创建任务
func (c *TaskBoardServiceHTTPClientImpl) CreateTask(ctx context.Context, in *CreateTaskReq, opts ...http.CallOption) (*CreateTaskReply, error) {
	var out CreateTaskReply
	pattern := "/api/v1/tasks"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTaskBoardServiceCreateTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteTask 删除任务
func (c *TaskBoardServiceHTTPClientImpl) DeleteTask(ctx context.Context, in *DeleteTaskReq, opts ...http.CallOption) (*DeleteTaskReply, error) {
	var out DeleteTaskReply
	pattern := "/api/v1/tasks/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskBoardServiceDeleteTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ExecuteTaskRuleChain 执行任务关联的规则链
func (c *TaskBoardServiceHTTPClientImpl) ExecuteTaskRuleChain(ctx context.Context, in *ExecuteTaskRuleChainReq, opts ...http.CallOption) (*ExecuteTaskRuleChainReply, error) {
	var out ExecuteTaskRuleChainReply
	pattern := "/api/v1/tasks/{id}/execute"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTaskBoardServiceExecuteTaskRuleChain))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTask 获取任务详情
func (c *TaskBoardServiceHTTPClientImpl) GetTask(ctx context.Context, in *GetTaskReq, opts ...http.CallOption) (*GetTaskReply, error) {
	var out GetTaskReply
	pattern := "/api/v1/tasks/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskBoardServiceGetTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListChildTasks 查询子任务列表
func (c *TaskBoardServiceHTTPClientImpl) ListChildTasks(ctx context.Context, in *ListChildTasksReq, opts ...http.CallOption) (*ListChildTasksReply, error) {
	var out ListChildTasksReply
	pattern := "/api/v1/tasks/{parent_id}/children"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskBoardServiceListChildTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTasks 查询任务列表
func (c *TaskBoardServiceHTTPClientImpl) ListTasks(ctx context.Context, in *ListTasksReq, opts ...http.CallOption) (*ListTasksReply, error) {
	var out ListTasksReply
	pattern := "/api/v1/tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskBoardServiceListTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateTask 更新任务
func (c *TaskBoardServiceHTTPClientImpl) UpdateTask(ctx context.Context, in *UpdateTaskReq, opts ...http.CallOption) (*UpdateTaskReply, error) {
	var out UpdateTaskReply
	pattern := "/api/v1/tasks/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTaskBoardServiceUpdateTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationServiceManagementServiceCreateService = "/rulego.v1.ServiceManagementService/CreateService"
const OperationServiceManagementServiceDeleteService = "/rulego.v1.ServiceManagementService/DeleteService"
const OperationServiceManagementServiceGetService = "/rulego.v1.ServiceManagementService/GetService"
const OperationServiceManagementServiceListServices = "/rulego.v1.ServiceManagementService/ListServices"
const OperationServiceManagementServiceUpdateService = "/rulego.v1.ServiceManagementService/UpdateService"

type ServiceManagementServiceHTTPServer interface {
	// CreateService 创建服务
	CreateService(context.Context, *CreateServiceReq) (*CreateServiceReply, error)
	// DeleteService 删除服务
	DeleteService(context.Context, *DeleteServiceReq) (*DeleteServiceReply, error)
	// GetService 获取服务详情
	GetService(context.Context, *GetServiceReq) (*GetServiceReply, error)
	// ListServices 查询服务列表
	ListServices(context.Context, *ListServicesReq) (*ListServicesReply, error)
	// UpdateService 更新服务
	UpdateService(context.Context, *UpdateServiceReq) (*UpdateServiceReply, error)
}

func RegisterServiceManagementServiceHTTPServer(s *http.Server, srv ServiceManagementServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/services", _ServiceManagementService_CreateService0_HTTP_Handler(srv))
	r.GET("/api/v1/services/{id}", _ServiceManagementService_GetService0_HTTP_Handler(srv))
	r.GET("/api/v1/services", _ServiceManagementService_ListServices0_HTTP_Handler(srv))
	r.PUT("/api/v1/services/{id}", _ServiceManagementService_UpdateService0_HTTP_Handler(srv))
	r.DELETE("/api/v1/services/{id}", _ServiceManagementService_DeleteService0_HTTP_Handler(srv))
}

func _ServiceManagementService_CreateService0_HTTP_Handler(srv ServiceManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateServiceReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceManagementServiceCreateService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateService(ctx, req.(*CreateServiceReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateServiceReply)
		return ctx.Result(200, reply)
	}
}

func _ServiceManagementService_GetService0_HTTP_Handler(srv ServiceManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetServiceReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceManagementServiceGetService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetService(ctx, req.(*GetServiceReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetServiceReply)
		return ctx.Result(200, reply)
	}
}

func _ServiceManagementService_ListServices0_HTTP_Handler(srv ServiceManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListServicesReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceManagementServiceListServices)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListServices(ctx, req.(*ListServicesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListServicesReply)
		return ctx.Result(200, reply)
	}
}

func _ServiceManagementService_UpdateService0_HTTP_Handler(srv ServiceManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateServiceReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceManagementServiceUpdateService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateService(ctx, req.(*UpdateServiceReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateServiceReply)
		return ctx.Result(200, reply)
	}
}

func _ServiceManagementService_DeleteService0_HTTP_Handler(srv ServiceManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteServiceReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceManagementServiceDeleteService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteService(ctx, req.(*DeleteServiceReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteServiceReply)
		return ctx.Result(200, reply)
	}
}

type ServiceManagementServiceHTTPClient interface {
	// CreateService 创建服务
	CreateService(ctx context.Context, req *CreateServiceReq, opts ...http.CallOption) (rsp *CreateServiceReply, err error)
	// DeleteService 删除服务
	DeleteService(ctx context.Context, req *DeleteServiceReq, opts ...http.CallOption) (rsp *DeleteServiceReply, err error)
	// GetService 获取服务详情
	GetService(ctx context.Context, req *GetServiceReq, opts ...http.CallOption) (rsp *GetServiceReply, err error)
	// ListServices 查询服务列表
	ListServices(ctx context.Context, req *ListServicesReq, opts ...http.CallOption) (rsp *ListServicesReply, err error)
	// UpdateService 更新服务
	UpdateService(ctx context.Context, req *UpdateServiceReq, opts ...http.CallOption) (rsp *UpdateServiceReply, err error)
}

type ServiceManagementServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewServiceManagementServiceHTTPClient(client *http.Client) ServiceManagementServiceHTTPClient {
	return &ServiceManagementServiceHTTPClientImpl{client}
}

// CreateService 创建服务
func (c *ServiceManagementServiceHTTPClientImpl) CreateService(ctx context.Context, in *CreateServiceReq, opts ...http.CallOption) (*CreateServiceReply, error) {
	var out CreateServiceReply
	pattern := "/api/v1/services"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationServiceManagementServiceCreateService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteService 删除服务
func (c *ServiceManagementServiceHTTPClientImpl) DeleteService(ctx context.Context, in *DeleteServiceReq, opts ...http.CallOption) (*DeleteServiceReply, error) {
	var out DeleteServiceReply
	pattern := "/api/v1/services/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServiceManagementServiceDeleteService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetService 获取服务详情
func (c *ServiceManagementServiceHTTPClientImpl) GetService(ctx context.Context, in *GetServiceReq, opts ...http.CallOption) (*GetServiceReply, error) {
	var out GetServiceReply
	pattern := "/api/v1/services/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServiceManagementServiceGetService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListServices 查询服务列表
func (c *ServiceManagementServiceHTTPClientImpl) ListServices(ctx context.Context, in *ListServicesReq, opts ...http.CallOption) (*ListServicesReply, error) {
	var out ListServicesReply
	pattern := "/api/v1/services"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServiceManagementServiceListServices))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateService 更新服务
func (c *ServiceManagementServiceHTTPClientImpl) UpdateService(ctx context.Context, in *UpdateServiceReq, opts ...http.CallOption) (*UpdateServiceReply, error) {
	var out UpdateServiceReply
	pattern := "/api/v1/services/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationServiceManagementServiceUpdateService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
