// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Ai            *AI                    `protobuf:"bytes,3,opt,name=ai,proto3" json:"ai,omitempty"`
	Agent         *Agent                 `protobuf:"bytes,4,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetAi() *AI {
	if x != nil {
		return x.Ai
	}
	return nil
}

func (x *Bootstrap) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redis         *Data_Redis            `protobuf:"bytes,1,opt,name=redis,proto3" json:"redis,omitempty"`
	Postgres      *Data_Postgres         `protobuf:"bytes,2,opt,name=postgres,proto3" json:"postgres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetPostgres() *Data_Postgres {
	if x != nil {
		return x.Postgres
	}
	return nil
}

type AI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doubao        *AI_DouBao             `protobuf:"bytes,1,opt,name=doubao,proto3" json:"doubao,omitempty"`
	Openai        *AI_OpenAI             `protobuf:"bytes,2,opt,name=openai,proto3" json:"openai,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AI) Reset() {
	*x = AI{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AI) ProtoMessage() {}

func (x *AI) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AI.ProtoReflect.Descriptor instead.
func (*AI) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *AI) GetDoubao() *AI_DouBao {
	if x != nil {
		return x.Doubao
	}
	return nil
}

func (x *AI) GetOpenai() *AI_OpenAI {
	if x != nil {
		return x.Openai
	}
	return nil
}

type Agent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SystemPrompt string                 `protobuf:"bytes,1,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	// Agent 内置读/写文件与 shell 的根目录；空则回退为 skill.dir，再空则为进程工作目录
	WorkspaceRoot string `protobuf:"bytes,3,opt,name=workspace_root,json=workspaceRoot,proto3" json:"workspace_root,omitempty"`
	// 管理端 RunTerminal 单条命令超时；未设置或 <=0 时默认 120s
	TerminalExecTimeout *durationpb.Duration `protobuf:"bytes,4,opt,name=terminal_exec_timeout,json=terminalExecTimeout,proto3" json:"terminal_exec_timeout,omitempty"`
	// 飞书 lark-cli 配置文件路径；空则使用 $HOME/.lark-cli/config.json（可用 ~ 前缀）
	LarkCliConfigPath string         `protobuf:"bytes,5,opt,name=lark_cli_config_path,json=larkCliConfigPath,proto3" json:"lark_cli_config_path,omitempty"`
	Skill             *Agent_Skill   `protobuf:"bytes,2,opt,name=skill,proto3" json:"skill,omitempty"`
	Memory            *Agent_Memory  `protobuf:"bytes,6,opt,name=memory,proto3" json:"memory,omitempty"`
	Context           *Agent_Context `protobuf:"bytes,7,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Agent) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *Agent) GetWorkspaceRoot() string {
	if x != nil {
		return x.WorkspaceRoot
	}
	return ""
}

func (x *Agent) GetTerminalExecTimeout() *durationpb.Duration {
	if x != nil {
		return x.TerminalExecTimeout
	}
	return nil
}

func (x *Agent) GetLarkCliConfigPath() string {
	if x != nil {
		return x.LarkCliConfigPath
	}
	return ""
}

func (x *Agent) GetSkill() *Agent_Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

func (x *Agent) GetMemory() *Agent_Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *Agent) GetContext() *Agent_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

type Data_Postgres struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Dbname        string                 `protobuf:"bytes,5,opt,name=dbname,proto3" json:"dbname,omitempty"`
	Sslmode       string                 `protobuf:"bytes,6,opt,name=sslmode,proto3" json:"sslmode,omitempty"`
	Timezone      string                 `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Postgres) Reset() {
	*x = Data_Postgres{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Postgres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Postgres) ProtoMessage() {}

func (x *Data_Postgres) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Postgres.ProtoReflect.Descriptor instead.
func (*Data_Postgres) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Postgres) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Data_Postgres) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Data_Postgres) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Data_Postgres) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Postgres) GetDbname() string {
	if x != nil {
		return x.Dbname
	}
	return ""
}

func (x *Data_Postgres) GetSslmode() string {
	if x != nil {
		return x.Sslmode
	}
	return ""
}

func (x *Data_Postgres) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type AI_DouBao struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiBaseUrl    string                 `protobuf:"bytes,3,opt,name=api_base_url,json=apiBaseUrl,proto3" json:"api_base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AI_DouBao) Reset() {
	*x = AI_DouBao{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AI_DouBao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AI_DouBao) ProtoMessage() {}

func (x *AI_DouBao) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AI_DouBao.ProtoReflect.Descriptor instead.
func (*AI_DouBao) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *AI_DouBao) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AI_DouBao) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AI_DouBao) GetApiBaseUrl() string {
	if x != nil {
		return x.ApiBaseUrl
	}
	return ""
}

type AI_OpenAI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiBaseUrl    string                 `protobuf:"bytes,3,opt,name=api_base_url,json=apiBaseUrl,proto3" json:"api_base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AI_OpenAI) Reset() {
	*x = AI_OpenAI{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AI_OpenAI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AI_OpenAI) ProtoMessage() {}

func (x *AI_OpenAI) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AI_OpenAI.ProtoReflect.Descriptor instead.
func (*AI_OpenAI) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *AI_OpenAI) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AI_OpenAI) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AI_OpenAI) GetApiBaseUrl() string {
	if x != nil {
		return x.ApiBaseUrl
	}
	return ""
}

type Agent_Memory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 记忆文件存储目录；空则默认 ~/.claude/memory
	Dir string `protobuf:"bytes,11,opt,name=dir,proto3" json:"dir,omitempty"`
	// 记忆条目 TTL（天）；<=0 表示不启用 TTL 清理
	EntryTtlDays             int32 `protobuf:"varint,12,opt,name=entry_ttl_days,json=entryTtlDays,proto3" json:"entry_ttl_days,omitempty"`
	UserPreferencesLimit     int32 `protobuf:"varint,1,opt,name=user_preferences_limit,json=userPreferencesLimit,proto3" json:"user_preferences_limit,omitempty"`
	UserFeedbackLimit        int32 `protobuf:"varint,2,opt,name=user_feedback_limit,json=userFeedbackLimit,proto3" json:"user_feedback_limit,omitempty"`
	ProjectFactsLimit        int32 `protobuf:"varint,3,opt,name=project_facts_limit,json=projectFactsLimit,proto3" json:"project_facts_limit,omitempty"`
	ProjectDecisionsLimit    int32 `protobuf:"varint,4,opt,name=project_decisions_limit,json=projectDecisionsLimit,proto3" json:"project_decisions_limit,omitempty"`
	ProjectSummariesLimit    int32 `protobuf:"varint,5,opt,name=project_summaries_limit,json=projectSummariesLimit,proto3" json:"project_summaries_limit,omitempty"`
	MaxUserPreferencesLimit  int32 `protobuf:"varint,6,opt,name=max_user_preferences_limit,json=maxUserPreferencesLimit,proto3" json:"max_user_preferences_limit,omitempty"`
	MaxUserFeedbackLimit     int32 `protobuf:"varint,7,opt,name=max_user_feedback_limit,json=maxUserFeedbackLimit,proto3" json:"max_user_feedback_limit,omitempty"`
	MaxProjectFactsLimit     int32 `protobuf:"varint,8,opt,name=max_project_facts_limit,json=maxProjectFactsLimit,proto3" json:"max_project_facts_limit,omitempty"`
	MaxProjectDecisionsLimit int32 `protobuf:"varint,9,opt,name=max_project_decisions_limit,json=maxProjectDecisionsLimit,proto3" json:"max_project_decisions_limit,omitempty"`
	MaxProjectSummariesLimit int32 `protobuf:"varint,10,opt,name=max_project_summaries_limit,json=maxProjectSummariesLimit,proto3" json:"max_project_summaries_limit,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Agent_Memory) Reset() {
	*x = Agent_Memory{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent_Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent_Memory) ProtoMessage() {}

func (x *Agent_Memory) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent_Memory.ProtoReflect.Descriptor instead.
func (*Agent_Memory) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Agent_Memory) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *Agent_Memory) GetEntryTtlDays() int32 {
	if x != nil {
		return x.EntryTtlDays
	}
	return 0
}

func (x *Agent_Memory) GetUserPreferencesLimit() int32 {
	if x != nil {
		return x.UserPreferencesLimit
	}
	return 0
}

func (x *Agent_Memory) GetUserFeedbackLimit() int32 {
	if x != nil {
		return x.UserFeedbackLimit
	}
	return 0
}

func (x *Agent_Memory) GetProjectFactsLimit() int32 {
	if x != nil {
		return x.ProjectFactsLimit
	}
	return 0
}

func (x *Agent_Memory) GetProjectDecisionsLimit() int32 {
	if x != nil {
		return x.ProjectDecisionsLimit
	}
	return 0
}

func (x *Agent_Memory) GetProjectSummariesLimit() int32 {
	if x != nil {
		return x.ProjectSummariesLimit
	}
	return 0
}

func (x *Agent_Memory) GetMaxUserPreferencesLimit() int32 {
	if x != nil {
		return x.MaxUserPreferencesLimit
	}
	return 0
}

func (x *Agent_Memory) GetMaxUserFeedbackLimit() int32 {
	if x != nil {
		return x.MaxUserFeedbackLimit
	}
	return 0
}

func (x *Agent_Memory) GetMaxProjectFactsLimit() int32 {
	if x != nil {
		return x.MaxProjectFactsLimit
	}
	return 0
}

func (x *Agent_Memory) GetMaxProjectDecisionsLimit() int32 {
	if x != nil {
		return x.MaxProjectDecisionsLimit
	}
	return 0
}

func (x *Agent_Memory) GetMaxProjectSummariesLimit() int32 {
	if x != nil {
		return x.MaxProjectSummariesLimit
	}
	return 0
}

type Agent_Context struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MemoryEnabled      bool                   `protobuf:"varint,1,opt,name=memory_enabled,json=memoryEnabled,proto3" json:"memory_enabled,omitempty"`
	SummaryThreshold   int32                  `protobuf:"varint,2,opt,name=summary_threshold,json=summaryThreshold,proto3" json:"summary_threshold,omitempty"`
	MaxHistoryMessages int32                  `protobuf:"varint,3,opt,name=max_history_messages,json=maxHistoryMessages,proto3" json:"max_history_messages,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Agent_Context) Reset() {
	*x = Agent_Context{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent_Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent_Context) ProtoMessage() {}

func (x *Agent_Context) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent_Context.ProtoReflect.Descriptor instead.
func (*Agent_Context) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Agent_Context) GetMemoryEnabled() bool {
	if x != nil {
		return x.MemoryEnabled
	}
	return false
}

func (x *Agent_Context) GetSummaryThreshold() int32 {
	if x != nil {
		return x.SummaryThreshold
	}
	return 0
}

func (x *Agent_Context) GetMaxHistoryMessages() int32 {
	if x != nil {
		return x.MaxHistoryMessages
	}
	return 0
}

type Agent_Skill struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Dir            string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Dirs           string                 `protobuf:"bytes,2,opt,name=dirs,proto3" json:"dirs,omitempty"`
	Namespace      string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Allowlist      string                 `protobuf:"bytes,4,opt,name=allowlist,proto3" json:"allowlist,omitempty"`
	HotReload      bool                   `protobuf:"varint,5,opt,name=hot_reload,json=hotReload,proto3" json:"hot_reload,omitempty"`
	ScanIntervalMs int32                  `protobuf:"varint,6,opt,name=scan_interval_ms,json=scanIntervalMs,proto3" json:"scan_interval_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Agent_Skill) Reset() {
	*x = Agent_Skill{}
	mi := &file_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent_Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent_Skill) ProtoMessage() {}

func (x *Agent_Skill) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent_Skill.ProtoReflect.Descriptor instead.
func (*Agent_Skill) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 2}
}

func (x *Agent_Skill) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *Agent_Skill) GetDirs() string {
	if x != nil {
		return x.Dirs
	}
	return ""
}

func (x *Agent_Skill) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Agent_Skill) GetAllowlist() string {
	if x != nil {
		return x.Allowlist
	}
	return ""
}

func (x *Agent_Skill) GetHotReload() bool {
	if x != nil {
		return x.HotReload
	}
	return false
}

func (x *Agent_Skill) GetScanIntervalMs() int32 {
	if x != nil {
		return x.ScanIntervalMs
	}
	return 0
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xa6\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12\x1e\n" +
	"\x02ai\x18\x03 \x01(\v2\x0e.kratos.api.AIR\x02ai\x12'\n" +
	"\x05agent\x18\x04 \x01(\v2\x11.kratos.api.AgentR\x05agent\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xd4\x03\n" +
	"\x04Data\x12,\n" +
	"\x05redis\x18\x01 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x125\n" +
	"\bpostgres\x18\x02 \x01(\v2\x19.kratos.api.Data.PostgresR\bpostgres\x1a\xb3\x01\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x1a\xb0\x01\n" +
	"\bPostgres\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x16\n" +
	"\x06dbname\x18\x05 \x01(\tR\x06dbname\x12\x18\n" +
	"\asslmode\x18\x06 \x01(\tR\asslmode\x12\x1a\n" +
	"\btimezone\x18\a \x01(\tR\btimezone\"\x98\x02\n" +
	"\x02AI\x12-\n" +
	"\x06doubao\x18\x01 \x01(\v2\x15.kratos.api.AI.DouBaoR\x06doubao\x12-\n" +
	"\x06openai\x18\x02 \x01(\v2\x15.kratos.api.AI.OpenAIR\x06openai\x1aY\n" +
	"\x06DouBao\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12 \n" +
	"\fapi_base_url\x18\x03 \x01(\tR\n" +
	"apiBaseUrl\x1aY\n" +
	"\x06OpenAI\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12 \n" +
	"\fapi_base_url\x18\x03 \x01(\tR\n" +
	"apiBaseUrl\"\xa2\n" +
	"\n" +
	"\x05Agent\x12#\n" +
	"\rsystem_prompt\x18\x01 \x01(\tR\fsystemPrompt\x12%\n" +
	"\x0eworkspace_root\x18\x03 \x01(\tR\rworkspaceRoot\x12M\n" +
	"\x15terminal_exec_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x13terminalExecTimeout\x12/\n" +
	"\x14lark_cli_config_path\x18\x05 \x01(\tR\x11larkCliConfigPath\x12-\n" +
	"\x05skill\x18\x02 \x01(\v2\x17.kratos.api.Agent.SkillR\x05skill\x120\n" +
	"\x06memory\x18\x06 \x01(\v2\x18.kratos.api.Agent.MemoryR\x06memory\x123\n" +
	"\acontext\x18\a \x01(\v2\x19.kratos.api.Agent.ContextR\acontext\x1a\xef\x04\n" +
	"\x06Memory\x12\x10\n" +
	"\x03dir\x18\v \x01(\tR\x03dir\x12$\n" +
	"\x0eentry_ttl_days\x18\f \x01(\x05R\fentryTtlDays\x124\n" +
	"\x16user_preferences_limit\x18\x01 \x01(\x05R\x14userPreferencesLimit\x12.\n" +
	"\x13user_feedback_limit\x18\x02 \x01(\x05R\x11userFeedbackLimit\x12.\n" +
	"\x13project_facts_limit\x18\x03 \x01(\x05R\x11projectFactsLimit\x126\n" +
	"\x17project_decisions_limit\x18\x04 \x01(\x05R\x15projectDecisionsLimit\x126\n" +
	"\x17project_summaries_limit\x18\x05 \x01(\x05R\x15projectSummariesLimit\x12;\n" +
	"\x1amax_user_preferences_limit\x18\x06 \x01(\x05R\x17maxUserPreferencesLimit\x125\n" +
	"\x17max_user_feedback_limit\x18\a \x01(\x05R\x14maxUserFeedbackLimit\x125\n" +
	"\x17max_project_facts_limit\x18\b \x01(\x05R\x14maxProjectFactsLimit\x12=\n" +
	"\x1bmax_project_decisions_limit\x18\t \x01(\x05R\x18maxProjectDecisionsLimit\x12=\n" +
	"\x1bmax_project_summaries_limit\x18\n" +
	" \x01(\x05R\x18maxProjectSummariesLimit\x1a\x8f\x01\n" +
	"\aContext\x12%\n" +
	"\x0ememory_enabled\x18\x01 \x01(\bR\rmemoryEnabled\x12+\n" +
	"\x11summary_threshold\x18\x02 \x01(\x05R\x10summaryThreshold\x120\n" +
	"\x14max_history_messages\x18\x03 \x01(\x05R\x12maxHistoryMessages\x1a\xb2\x01\n" +
	"\x05Skill\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12\x12\n" +
	"\x04dirs\x18\x02 \x01(\tR\x04dirs\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1c\n" +
	"\tallowlist\x18\x04 \x01(\tR\tallowlist\x12\x1d\n" +
	"\n" +
	"hot_reload\x18\x05 \x01(\bR\thotReload\x12(\n" +
	"\x10scan_interval_ms\x18\x06 \x01(\x05R\x0escanIntervalMsB!Z\x1fruleGoKratos/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Data)(nil),                // 2: kratos.api.Data
	(*AI)(nil),                  // 3: kratos.api.AI
	(*Agent)(nil),               // 4: kratos.api.Agent
	(*Server_HTTP)(nil),         // 5: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 6: kratos.api.Server.GRPC
	(*Data_Redis)(nil),          // 7: kratos.api.Data.Redis
	(*Data_Postgres)(nil),       // 8: kratos.api.Data.Postgres
	(*AI_DouBao)(nil),           // 9: kratos.api.AI.DouBao
	(*AI_OpenAI)(nil),           // 10: kratos.api.AI.OpenAI
	(*Agent_Memory)(nil),        // 11: kratos.api.Agent.Memory
	(*Agent_Context)(nil),       // 12: kratos.api.Agent.Context
	(*Agent_Skill)(nil),         // 13: kratos.api.Agent.Skill
	(*durationpb.Duration)(nil), // 14: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Bootstrap.ai:type_name -> kratos.api.AI
	4,  // 3: kratos.api.Bootstrap.agent:type_name -> kratos.api.Agent
	5,  // 4: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	6,  // 5: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	7,  // 6: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	8,  // 7: kratos.api.Data.postgres:type_name -> kratos.api.Data.Postgres
	9,  // 8: kratos.api.AI.doubao:type_name -> kratos.api.AI.DouBao
	10, // 9: kratos.api.AI.openai:type_name -> kratos.api.AI.OpenAI
	14, // 10: kratos.api.Agent.terminal_exec_timeout:type_name -> google.protobuf.Duration
	13, // 11: kratos.api.Agent.skill:type_name -> kratos.api.Agent.Skill
	11, // 12: kratos.api.Agent.memory:type_name -> kratos.api.Agent.Memory
	12, // 13: kratos.api.Agent.context:type_name -> kratos.api.Agent.Context
	14, // 14: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	14, // 15: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	14, // 16: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	14, // 17: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
