// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: api/playground/v1/playground.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAgentPlaygroundCreateAgentPool = "/playground.v1.AgentPlayground/CreateAgentPool"
const OperationAgentPlaygroundCreateScheme = "/playground.v1.AgentPlayground/CreateScheme"
const OperationAgentPlaygroundDeleteScheme = "/playground.v1.AgentPlayground/DeleteScheme"
const OperationAgentPlaygroundGetAgentPool = "/playground.v1.AgentPlayground/GetAgentPool"
const OperationAgentPlaygroundGetCollaborationModes = "/playground.v1.AgentPlayground/GetCollaborationModes"
const OperationAgentPlaygroundGetRun = "/playground.v1.AgentPlayground/GetRun"
const OperationAgentPlaygroundGetRunEvents = "/playground.v1.AgentPlayground/GetRunEvents"
const OperationAgentPlaygroundGetScheme = "/playground.v1.AgentPlayground/GetScheme"
const OperationAgentPlaygroundListAgentPools = "/playground.v1.AgentPlayground/ListAgentPools"
const OperationAgentPlaygroundListSchemes = "/playground.v1.AgentPlayground/ListSchemes"
const OperationAgentPlaygroundRunWorkflow = "/playground.v1.AgentPlayground/RunWorkflow"
const OperationAgentPlaygroundUpdateAgentPool = "/playground.v1.AgentPlayground/UpdateAgentPool"
const OperationAgentPlaygroundUpdateScheme = "/playground.v1.AgentPlayground/UpdateScheme"

type AgentPlaygroundHTTPServer interface {
	// CreateAgentPool 创建 Agent 池
	CreateAgentPool(context.Context, *CreateAgentPoolReq) (*CreateAgentPoolReply, error)
	// CreateScheme 创建协作方案
	CreateScheme(context.Context, *CreateSchemeReq) (*CreateSchemeReply, error)
	// DeleteScheme 删除协作方案
	DeleteScheme(context.Context, *DeleteSchemeReq) (*DeleteSchemeReply, error)
	// GetAgentPool 获取单个 Agent 池
	GetAgentPool(context.Context, *GetAgentPoolReq) (*GetAgentPoolReply, error)
	// GetCollaborationModes 获取可用协作模式
	GetCollaborationModes(context.Context, *GetCollaborationModesReq) (*GetCollaborationModesReply, error)
	// GetRun 获取运行结果
	GetRun(context.Context, *GetRunReq) (*GetRunReply, error)
	// GetRunEvents 获取运行事件（用于 Trace）
	GetRunEvents(context.Context, *GetRunEventsReq) (*GetRunEventsReply, error)
	// GetScheme 获取单个协作方案
	GetScheme(context.Context, *GetSchemeReq) (*GetSchemeReply, error)
	// ListAgentPools 获取 Agent 池列表
	ListAgentPools(context.Context, *ListAgentPoolsReq) (*ListAgentPoolsReply, error)
	// ListSchemes 获取协作方案列表
	ListSchemes(context.Context, *ListSchemesReq) (*ListSchemesReply, error)
	// RunWorkflow 运行工作流
	RunWorkflow(context.Context, *RunWorkflowReq) (*RunWorkflowReply, error)
	// UpdateAgentPool 更新 Agent 池
	UpdateAgentPool(context.Context, *UpdateAgentPoolReq) (*UpdateAgentPoolReply, error)
	// UpdateScheme 更新协作方案
	UpdateScheme(context.Context, *UpdateSchemeReq) (*UpdateSchemeReply, error)
}

func RegisterAgentPlaygroundHTTPServer(s *http.Server, srv AgentPlaygroundHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/playground/pools", _AgentPlayground_ListAgentPools0_HTTP_Handler(srv))
	r.GET("/api/v1/playground/pools/{id}", _AgentPlayground_GetAgentPool0_HTTP_Handler(srv))
	r.POST("/api/v1/playground/pools", _AgentPlayground_CreateAgentPool0_HTTP_Handler(srv))
	r.PUT("/api/v1/playground/pools/{id}", _AgentPlayground_UpdateAgentPool0_HTTP_Handler(srv))
	r.GET("/api/v1/playground/schemes", _AgentPlayground_ListSchemes0_HTTP_Handler(srv))
	r.GET("/api/v1/playground/schemes/{id}", _AgentPlayground_GetScheme0_HTTP_Handler(srv))
	r.POST("/api/v1/playground/schemes", _AgentPlayground_CreateScheme0_HTTP_Handler(srv))
	r.PUT("/api/v1/playground/schemes/{id}", _AgentPlayground_UpdateScheme0_HTTP_Handler(srv))
	r.DELETE("/api/v1/playground/schemes/{id}", _AgentPlayground_DeleteScheme0_HTTP_Handler(srv))
	r.POST("/api/v1/playground/run", _AgentPlayground_RunWorkflow0_HTTP_Handler(srv))
	r.GET("/api/v1/playground/run/{run_id}", _AgentPlayground_GetRun0_HTTP_Handler(srv))
	r.GET("/api/v1/playground/run/{run_id}/events", _AgentPlayground_GetRunEvents0_HTTP_Handler(srv))
	r.GET("/api/v1/playground/modes", _AgentPlayground_GetCollaborationModes0_HTTP_Handler(srv))
}

func _AgentPlayground_ListAgentPools0_HTTP_Handler(srv AgentPlaygroundHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAgentPoolsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentPlaygroundListAgentPools)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAgentPools(ctx, req.(*ListAgentPoolsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAgentPoolsReply)
		return ctx.Result(200, reply)
	}
}

func _AgentPlayground_GetAgentPool0_HTTP_Handler(srv AgentPlaygroundHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAgentPoolReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentPlaygroundGetAgentPool)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAgentPool(ctx, req.(*GetAgentPoolReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAgentPoolReply)
		return ctx.Result(200, reply)
	}
}

func _AgentPlayground_CreateAgentPool0_HTTP_Handler(srv AgentPlaygroundHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAgentPoolReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentPlaygroundCreateAgentPool)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAgentPool(ctx, req.(*CreateAgentPoolReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAgentPoolReply)
		return ctx.Result(200, reply)
	}
}

func _AgentPlayground_UpdateAgentPool0_HTTP_Handler(srv AgentPlaygroundHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAgentPoolReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentPlaygroundUpdateAgentPool)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAgentPool(ctx, req.(*UpdateAgentPoolReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateAgentPoolReply)
		return ctx.Result(200, reply)
	}
}

func _AgentPlayground_ListSchemes0_HTTP_Handler(srv AgentPlaygroundHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSchemesReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentPlaygroundListSchemes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSchemes(ctx, req.(*ListSchemesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSchemesReply)
		return ctx.Result(200, reply)
	}
}

func _AgentPlayground_GetScheme0_HTTP_Handler(srv AgentPlaygroundHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSchemeReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentPlaygroundGetScheme)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetScheme(ctx, req.(*GetSchemeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSchemeReply)
		return ctx.Result(200, reply)
	}
}

func _AgentPlayground_CreateScheme0_HTTP_Handler(srv AgentPlaygroundHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSchemeReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentPlaygroundCreateScheme)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateScheme(ctx, req.(*CreateSchemeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSchemeReply)
		return ctx.Result(200, reply)
	}
}

func _AgentPlayground_UpdateScheme0_HTTP_Handler(srv AgentPlaygroundHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSchemeReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentPlaygroundUpdateScheme)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateScheme(ctx, req.(*UpdateSchemeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateSchemeReply)
		return ctx.Result(200, reply)
	}
}

func _AgentPlayground_DeleteScheme0_HTTP_Handler(srv AgentPlaygroundHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSchemeReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentPlaygroundDeleteScheme)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteScheme(ctx, req.(*DeleteSchemeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteSchemeReply)
		return ctx.Result(200, reply)
	}
}

func _AgentPlayground_RunWorkflow0_HTTP_Handler(srv AgentPlaygroundHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RunWorkflowReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentPlaygroundRunWorkflow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RunWorkflow(ctx, req.(*RunWorkflowReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RunWorkflowReply)
		return ctx.Result(200, reply)
	}
}

func _AgentPlayground_GetRun0_HTTP_Handler(srv AgentPlaygroundHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRunReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentPlaygroundGetRun)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRun(ctx, req.(*GetRunReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRunReply)
		return ctx.Result(200, reply)
	}
}

func _AgentPlayground_GetRunEvents0_HTTP_Handler(srv AgentPlaygroundHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRunEventsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentPlaygroundGetRunEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRunEvents(ctx, req.(*GetRunEventsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRunEventsReply)
		return ctx.Result(200, reply)
	}
}

func _AgentPlayground_GetCollaborationModes0_HTTP_Handler(srv AgentPlaygroundHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCollaborationModesReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentPlaygroundGetCollaborationModes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCollaborationModes(ctx, req.(*GetCollaborationModesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCollaborationModesReply)
		return ctx.Result(200, reply)
	}
}

type AgentPlaygroundHTTPClient interface {
	// CreateAgentPool 创建 Agent 池
	CreateAgentPool(ctx context.Context, req *CreateAgentPoolReq, opts ...http.CallOption) (rsp *CreateAgentPoolReply, err error)
	// CreateScheme 创建协作方案
	CreateScheme(ctx context.Context, req *CreateSchemeReq, opts ...http.CallOption) (rsp *CreateSchemeReply, err error)
	// DeleteScheme 删除协作方案
	DeleteScheme(ctx context.Context, req *DeleteSchemeReq, opts ...http.CallOption) (rsp *DeleteSchemeReply, err error)
	// GetAgentPool 获取单个 Agent 池
	GetAgentPool(ctx context.Context, req *GetAgentPoolReq, opts ...http.CallOption) (rsp *GetAgentPoolReply, err error)
	// GetCollaborationModes 获取可用协作模式
	GetCollaborationModes(ctx context.Context, req *GetCollaborationModesReq, opts ...http.CallOption) (rsp *GetCollaborationModesReply, err error)
	// GetRun 获取运行结果
	GetRun(ctx context.Context, req *GetRunReq, opts ...http.CallOption) (rsp *GetRunReply, err error)
	// GetRunEvents 获取运行事件（用于 Trace）
	GetRunEvents(ctx context.Context, req *GetRunEventsReq, opts ...http.CallOption) (rsp *GetRunEventsReply, err error)
	// GetScheme 获取单个协作方案
	GetScheme(ctx context.Context, req *GetSchemeReq, opts ...http.CallOption) (rsp *GetSchemeReply, err error)
	// ListAgentPools 获取 Agent 池列表
	ListAgentPools(ctx context.Context, req *ListAgentPoolsReq, opts ...http.CallOption) (rsp *ListAgentPoolsReply, err error)
	// ListSchemes 获取协作方案列表
	ListSchemes(ctx context.Context, req *ListSchemesReq, opts ...http.CallOption) (rsp *ListSchemesReply, err error)
	// RunWorkflow 运行工作流
	RunWorkflow(ctx context.Context, req *RunWorkflowReq, opts ...http.CallOption) (rsp *RunWorkflowReply, err error)
	// UpdateAgentPool 更新 Agent 池
	UpdateAgentPool(ctx context.Context, req *UpdateAgentPoolReq, opts ...http.CallOption) (rsp *UpdateAgentPoolReply, err error)
	// UpdateScheme 更新协作方案
	UpdateScheme(ctx context.Context, req *UpdateSchemeReq, opts ...http.CallOption) (rsp *UpdateSchemeReply, err error)
}

type AgentPlaygroundHTTPClientImpl struct {
	cc *http.Client
}

func NewAgentPlaygroundHTTPClient(client *http.Client) AgentPlaygroundHTTPClient {
	return &AgentPlaygroundHTTPClientImpl{client}
}

// CreateAgentPool 创建 Agent 池
func (c *AgentPlaygroundHTTPClientImpl) CreateAgentPool(ctx context.Context, in *CreateAgentPoolReq, opts ...http.CallOption) (*CreateAgentPoolReply, error) {
	var out CreateAgentPoolReply
	pattern := "/api/v1/playground/pools"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentPlaygroundCreateAgentPool))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateScheme 创建协作方案
func (c *AgentPlaygroundHTTPClientImpl) CreateScheme(ctx context.Context, in *CreateSchemeReq, opts ...http.CallOption) (*CreateSchemeReply, error) {
	var out CreateSchemeReply
	pattern := "/api/v1/playground/schemes"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentPlaygroundCreateScheme))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteScheme 删除协作方案
func (c *AgentPlaygroundHTTPClientImpl) DeleteScheme(ctx context.Context, in *DeleteSchemeReq, opts ...http.CallOption) (*DeleteSchemeReply, error) {
	var out DeleteSchemeReply
	pattern := "/api/v1/playground/schemes/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentPlaygroundDeleteScheme))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAgentPool 获取单个 Agent 池
func (c *AgentPlaygroundHTTPClientImpl) GetAgentPool(ctx context.Context, in *GetAgentPoolReq, opts ...http.CallOption) (*GetAgentPoolReply, error) {
	var out GetAgentPoolReply
	pattern := "/api/v1/playground/pools/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentPlaygroundGetAgentPool))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCollaborationModes 获取可用协作模式
func (c *AgentPlaygroundHTTPClientImpl) GetCollaborationModes(ctx context.Context, in *GetCollaborationModesReq, opts ...http.CallOption) (*GetCollaborationModesReply, error) {
	var out GetCollaborationModesReply
	pattern := "/api/v1/playground/modes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentPlaygroundGetCollaborationModes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRun 获取运行结果
func (c *AgentPlaygroundHTTPClientImpl) GetRun(ctx context.Context, in *GetRunReq, opts ...http.CallOption) (*GetRunReply, error) {
	var out GetRunReply
	pattern := "/api/v1/playground/run/{run_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentPlaygroundGetRun))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRunEvents 获取运行事件（用于 Trace）
func (c *AgentPlaygroundHTTPClientImpl) GetRunEvents(ctx context.Context, in *GetRunEventsReq, opts ...http.CallOption) (*GetRunEventsReply, error) {
	var out GetRunEventsReply
	pattern := "/api/v1/playground/run/{run_id}/events"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentPlaygroundGetRunEvents))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetScheme 获取单个协作方案
func (c *AgentPlaygroundHTTPClientImpl) GetScheme(ctx context.Context, in *GetSchemeReq, opts ...http.CallOption) (*GetSchemeReply, error) {
	var out GetSchemeReply
	pattern := "/api/v1/playground/schemes/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentPlaygroundGetScheme))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAgentPools 获取 Agent 池列表
func (c *AgentPlaygroundHTTPClientImpl) ListAgentPools(ctx context.Context, in *ListAgentPoolsReq, opts ...http.CallOption) (*ListAgentPoolsReply, error) {
	var out ListAgentPoolsReply
	pattern := "/api/v1/playground/pools"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentPlaygroundListAgentPools))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSchemes 获取协作方案列表
func (c *AgentPlaygroundHTTPClientImpl) ListSchemes(ctx context.Context, in *ListSchemesReq, opts ...http.CallOption) (*ListSchemesReply, error) {
	var out ListSchemesReply
	pattern := "/api/v1/playground/schemes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentPlaygroundListSchemes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RunWorkflow 运行工作流
func (c *AgentPlaygroundHTTPClientImpl) RunWorkflow(ctx context.Context, in *RunWorkflowReq, opts ...http.CallOption) (*RunWorkflowReply, error) {
	var out RunWorkflowReply
	pattern := "/api/v1/playground/run"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentPlaygroundRunWorkflow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateAgentPool 更新 Agent 池
func (c *AgentPlaygroundHTTPClientImpl) UpdateAgentPool(ctx context.Context, in *UpdateAgentPoolReq, opts ...http.CallOption) (*UpdateAgentPoolReply, error) {
	var out UpdateAgentPoolReply
	pattern := "/api/v1/playground/pools/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentPlaygroundUpdateAgentPool))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateScheme 更新协作方案
func (c *AgentPlaygroundHTTPClientImpl) UpdateScheme(ctx context.Context, in *UpdateSchemeReq, opts ...http.CallOption) (*UpdateSchemeReply, error) {
	var out UpdateSchemeReply
	pattern := "/api/v1/playground/schemes/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentPlaygroundUpdateScheme))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
