server:
  http:
    addr: 0.0.0.0:8000
    timeout: 10000s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  postgres:
    host: ${DATA_POSTGRES_HOST}
    port: ${DATA_POSTGRES_PORT}
    user: ${DATA_POSTGRES_USER}
    password: ${DATA_POSTGRES_PASSWORD}
    dbname: ${DATA_POSTGRES_DBNAME}
    sslmode: ${DATA_POSTGRES_SSLMODE}
    timezone: ${DATA_POSTGRES_TIMEZONE}