server:
  http:
    addr: 0.0.0.0:8001
    timeout: 10000s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  postgres:
    host: ${DATA_POSTGRES_HOST}
    port: ${DATA_POSTGRES_PORT}
    user: ${DATA_POSTGRES_USER}
    password: ${DATA_POSTGRES_PASSWORD}
    dbname: ${DATA_POSTGRES_DBNAME}
    sslmode: ${DATA_POSTGRES_SSLMODE}
    timezone: ${DATA_POSTGRES_TIMEZONE}
ai:
  doubao:
    model: ${AI_DOUBAO_MODEL}
    api_key: ${AI_DOUBAO_API_KEY}
    api_base_url: ${AI_DOUBAO_BASE_URL}
  openai:
    model: ${AI_OPENAI_MODEL}
    api_key: ${AI_OPENAI_API_KEY}
    api_base_url: ${AI_OPENAI_BASE_URL}
